// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf_general.proto
// Protobuf C++ Version: 5.27.0

#include "protobuf_general.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr OpenhabLightEntity::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : openhab_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        openhab_dim_channel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        openhab_color_temperature_channel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        openhab_rgb_channel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        can_dim_{false},
        can_color_temperature_{false},
        can_rgb_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OpenhabLightEntity::OpenhabLightEntity(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct OpenhabLightEntityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OpenhabLightEntityDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OpenhabLightEntityDefaultTypeInternal() {}
  union {
    OpenhabLightEntity _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OpenhabLightEntityDefaultTypeInternal _OpenhabLightEntity_default_instance_;

inline constexpr NSPanelSettings::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rooms_{},
        _rooms_cached_byte_size_{0},
        scenes_{},
        _scenes_cached_byte_size_{0},
        mac_address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        button1_mqtt_topic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        button2_mqtt_topic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        button1_mqtt_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        button2_mqtt_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ip_address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        home_{0},
        default_page_{static_cast< ::NSPanelSettings_NSPanelDefaultPage >(0)},
        raise_to_100_light_level_{0},
        color_temp_min_{0},
        color_temp_max_{0},
        min_button_push_time_{0},
        button_long_press_time_{0},
        special_mode_trigger_time_{0},
        special_mode_release_time_{0},
        mqtt_ignore_time_{0},
        screen_dim_level_{0},
        screensaver_dim_level_{0},
        screensaver_activation_timeout_{0},
        screensaver_mode_{static_cast< ::NSPanelSettings_NSPanelScreensaverMode >(0)},
        reverse_color_temp_{false},
        is_us_panel_{false},
        lock_to_default_room_{false},
        reverse_relays_{false},
        clock_format_{static_cast< ::time_format >(0)},
        temperature_unit_{static_cast< ::temperature_format >(0)},
        temperature_calibration_{0},
        button1_mode_{static_cast< ::NSPanelSettings_NSPanelButtonMode >(0)},
        button2_mode_{static_cast< ::NSPanelSettings_NSPanelButtonMode >(0)},
        button1_detached_light_id_{0},
        button2_detached_light_id_{0},
        relay1_default_mode_{false},
        relay2_default_mode_{false},
        denied_{false},
        accepted_{false},
        relay1_register_type_{static_cast< ::NSPanelSettings_RelayRegisterType >(0)},
        relay2_register_type_{static_cast< ::NSPanelSettings_RelayRegisterType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR NSPanelSettings::NSPanelSettings(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NSPanelSettingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NSPanelSettingsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NSPanelSettingsDefaultTypeInternal() {}
  union {
    NSPanelSettings _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NSPanelSettingsDefaultTypeInternal _NSPanelSettings_default_instance_;

inline constexpr HomeAssistantEntity::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : home_assistant_entity_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        can_dim_{false},
        can_color_temperature_{false},
        can_rgb_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HomeAssistantEntity::HomeAssistantEntity(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HomeAssistantEntityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HomeAssistantEntityDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HomeAssistantEntityDefaultTypeInternal() {}
  union {
    HomeAssistantEntity _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HomeAssistantEntityDefaultTypeInternal _HomeAssistantEntity_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_protobuf_5fgeneral_2eproto[4];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protobuf_5fgeneral_2eproto = nullptr;
const ::uint32_t
    TableStruct_protobuf_5fgeneral_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::HomeAssistantEntity, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::HomeAssistantEntity, _impl_.home_assistant_entity_id_),
        PROTOBUF_FIELD_OFFSET(::HomeAssistantEntity, _impl_.can_dim_),
        PROTOBUF_FIELD_OFFSET(::HomeAssistantEntity, _impl_.can_color_temperature_),
        PROTOBUF_FIELD_OFFSET(::HomeAssistantEntity, _impl_.can_rgb_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _impl_.openhab_id_),
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _impl_.openhab_dim_channel_),
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _impl_.openhab_color_temperature_channel_),
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _impl_.openhab_rgb_channel_),
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _impl_.can_dim_),
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _impl_.can_color_temperature_),
        PROTOBUF_FIELD_OFFSET(::OpenhabLightEntity, _impl_.can_rgb_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.mac_address_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.home_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.default_page_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.raise_to_100_light_level_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.color_temp_min_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.color_temp_max_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.reverse_color_temp_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.min_button_push_time_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button_long_press_time_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.special_mode_trigger_time_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.special_mode_release_time_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.mqtt_ignore_time_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.screen_dim_level_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.screensaver_dim_level_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.screensaver_activation_timeout_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.screensaver_mode_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.clock_format_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.temperature_unit_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.is_us_panel_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.lock_to_default_room_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.reverse_relays_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.relay1_default_mode_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.relay2_default_mode_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.temperature_calibration_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button1_mode_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button2_mode_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button1_mqtt_topic_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button2_mqtt_topic_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button1_mqtt_payload_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button2_mqtt_payload_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button1_detached_light_id_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.button2_detached_light_id_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.denied_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.accepted_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.rooms_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.scenes_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.ip_address_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.relay1_register_type_),
        PROTOBUF_FIELD_OFFSET(::NSPanelSettings, _impl_.relay2_register_type_),
        4,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        1,
        2,
        3,
        5,
        6,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::HomeAssistantEntity)},
        {12, -1, -1, sizeof(::OpenhabLightEntity)},
        {27, 76, -1, sizeof(::NSPanelSettings)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_HomeAssistantEntity_default_instance_._instance,
    &::_OpenhabLightEntity_default_instance_._instance,
    &::_NSPanelSettings_default_instance_._instance,
};
const char descriptor_table_protodef_protobuf_5fgeneral_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026protobuf_general.proto\032\026protobuf_forma"
    "ts.proto\"x\n\023HomeAssistantEntity\022 \n\030home_"
    "assistant_entity_id\030\002 \001(\t\022\017\n\007can_dim\030\003 \001"
    "(\010\022\035\n\025can_color_temperature\030\004 \001(\010\022\017\n\007can"
    "_rgb\030\005 \001(\010\"\316\001\n\022OpenhabLightEntity\022\022\n\nope"
    "nhab_id\030\001 \001(\t\022\033\n\023openhab_dim_channel\030\002 \001"
    "(\t\022)\n!openhab_color_temperature_channel\030"
    "\003 \001(\t\022\033\n\023openhab_rgb_channel\030\004 \001(\t\022\017\n\007ca"
    "n_dim\030\005 \001(\010\022\035\n\025can_color_temperature\030\006 \001"
    "(\010\022\017\n\007can_rgb\030\007 \001(\010\"\366\016\n\017NSPanelSettings\022"
    "\017\n\002id\030\001 \001(\005H\000\210\001\001\022\023\n\013mac_address\030\002 \001(\t\022\014\n"
    "\004name\030\003 \001(\t\022\014\n\004home\030\004 \001(\005\0229\n\014default_pag"
    "e\030\005 \001(\0162#.NSPanelSettings.NSPanelDefault"
    "Page\022 \n\030raise_to_100_light_level\030\006 \001(\005\022\026"
    "\n\016color_temp_min\030\007 \001(\005\022\026\n\016color_temp_max"
    "\030\010 \001(\005\022\032\n\022reverse_color_temp\030\t \001(\010\022\034\n\024mi"
    "n_button_push_time\030\n \001(\005\022\036\n\026button_long_"
    "press_time\030\013 \001(\005\022!\n\031special_mode_trigger"
    "_time\030\014 \001(\005\022!\n\031special_mode_release_time"
    "\030\r \001(\005\022\030\n\020mqtt_ignore_time\030\016 \001(\005\022\030\n\020scre"
    "en_dim_level\030\017 \001(\005\022\035\n\025screensaver_dim_le"
    "vel\030\020 \001(\005\022&\n\036screensaver_activation_time"
    "out\030\021 \001(\005\022A\n\020screensaver_mode\030\022 \001(\0162\'.NS"
    "PanelSettings.NSPanelScreensaverMode\022\"\n\014"
    "clock_format\030\023 \001(\0162\014.time_format\022-\n\020temp"
    "erature_unit\030\024 \001(\0162\023.temperature_format\022"
    "\023\n\013is_us_panel\030\025 \001(\010\022\034\n\024lock_to_default_"
    "room\030\026 \001(\010\022\026\n\016reverse_relays\030\027 \001(\010\022\033\n\023re"
    "lay1_default_mode\030\030 \001(\010\022\033\n\023relay2_defaul"
    "t_mode\030\031 \001(\010\022\037\n\027temperature_calibration\030"
    "\032 \001(\005\0228\n\014button1_mode\030\033 \001(\0162\".NSPanelSet"
    "tings.NSPanelButtonMode\0228\n\014button2_mode\030"
    "\034 \001(\0162\".NSPanelSettings.NSPanelButtonMod"
    "e\022\037\n\022button1_mqtt_topic\030\035 \001(\tH\001\210\001\001\022\037\n\022bu"
    "tton2_mqtt_topic\030\036 \001(\tH\002\210\001\001\022!\n\024button1_m"
    "qtt_payload\030\037 \001(\tH\003\210\001\001\022!\n\024button2_mqtt_p"
    "ayload\030  \001(\tH\004\210\001\001\022&\n\031button1_detached_li"
    "ght_id\030! \001(\005H\005\210\001\001\022&\n\031button2_detached_li"
    "ght_id\030\" \001(\005H\006\210\001\001\022\016\n\006denied\030- \001(\010\022\020\n\010acc"
    "epted\030. \001(\010\022\r\n\005rooms\030/ \003(\005\022\016\n\006scenes\0300 \003"
    "(\005\022\022\n\nip_address\0301 \001(\t\022@\n\024relay1_registe"
    "r_type\0302 \001(\0162\".NSPanelSettings.RelayRegi"
    "sterType\022@\n\024relay2_register_type\0303 \001(\0162\""
    ".NSPanelSettings.RelayRegisterType\"C\n\022NS"
    "PanelDefaultPage\022\r\n\tMAIN_PAGE\020\000\022\017\n\013SCENE"
    "S_PAGE\020\001\022\r\n\tROOM_PAGE\020\002\"\250\001\n\026NSPanelScree"
    "nsaverMode\022\033\n\027WEATHER_WITH_BACKGROUND\020\000\022"
    "\036\n\032WEATHER_WITHOUT_BACKGROUND\020\001\022\034\n\030DATET"
    "IME_WITH_BACKGROUND\020\003\022\037\n\033DATETIME_WITHOU"
    "T_BACKGROUND\020\004\022\022\n\016NO_SCREENSAVER\020\005\"Y\n\021NS"
    "PanelButtonMode\022\017\n\013DIRECT_MODE\020\000\022\021\n\rDETA"
    "CHED_MODE\020\001\022\017\n\013CUSTOM_MQTT\020\002\022\017\n\013FOLLOW_M"
    "ODE\020\003\"*\n\021RelayRegisterType\022\n\n\006SWITCH\020\000\022\t"
    "\n\005LIGHT\020\001B\005\n\003_idB\025\n\023_button1_mqtt_topicB"
    "\025\n\023_button2_mqtt_topicB\027\n\025_button1_mqtt_"
    "payloadB\027\n\025_button2_mqtt_payloadB\034\n\032_but"
    "ton1_detached_light_idB\034\n\032_button2_detac"
    "hed_light_idb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_protobuf_5fgeneral_2eproto_deps[1] =
    {
        &::descriptor_table_protobuf_5fformats_2eproto,
};
static ::absl::once_flag descriptor_table_protobuf_5fgeneral_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protobuf_5fgeneral_2eproto = {
    false,
    false,
    2300,
    descriptor_table_protodef_protobuf_5fgeneral_2eproto,
    "protobuf_general.proto",
    &descriptor_table_protobuf_5fgeneral_2eproto_once,
    descriptor_table_protobuf_5fgeneral_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_protobuf_5fgeneral_2eproto::offsets,
    file_level_enum_descriptors_protobuf_5fgeneral_2eproto,
    file_level_service_descriptors_protobuf_5fgeneral_2eproto,
};
const ::google::protobuf::EnumDescriptor* NSPanelSettings_NSPanelDefaultPage_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protobuf_5fgeneral_2eproto);
  return file_level_enum_descriptors_protobuf_5fgeneral_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t NSPanelSettings_NSPanelDefaultPage_internal_data_[] = {
    196608u, 0u, };
bool NSPanelSettings_NSPanelDefaultPage_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr NSPanelSettings_NSPanelDefaultPage NSPanelSettings::MAIN_PAGE;
constexpr NSPanelSettings_NSPanelDefaultPage NSPanelSettings::SCENES_PAGE;
constexpr NSPanelSettings_NSPanelDefaultPage NSPanelSettings::ROOM_PAGE;
constexpr NSPanelSettings_NSPanelDefaultPage NSPanelSettings::NSPanelDefaultPage_MIN;
constexpr NSPanelSettings_NSPanelDefaultPage NSPanelSettings::NSPanelDefaultPage_MAX;
constexpr int NSPanelSettings::NSPanelDefaultPage_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* NSPanelSettings_NSPanelScreensaverMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protobuf_5fgeneral_2eproto);
  return file_level_enum_descriptors_protobuf_5fgeneral_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t NSPanelSettings_NSPanelScreensaverMode_internal_data_[] = {
    131072u, 32u, 14u, };
bool NSPanelSettings_NSPanelScreensaverMode_IsValid(int value) {
  return 0 <= value && value <= 5 && ((59u >> value) & 1) != 0;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr NSPanelSettings_NSPanelScreensaverMode NSPanelSettings::WEATHER_WITH_BACKGROUND;
constexpr NSPanelSettings_NSPanelScreensaverMode NSPanelSettings::WEATHER_WITHOUT_BACKGROUND;
constexpr NSPanelSettings_NSPanelScreensaverMode NSPanelSettings::DATETIME_WITH_BACKGROUND;
constexpr NSPanelSettings_NSPanelScreensaverMode NSPanelSettings::DATETIME_WITHOUT_BACKGROUND;
constexpr NSPanelSettings_NSPanelScreensaverMode NSPanelSettings::NO_SCREENSAVER;
constexpr NSPanelSettings_NSPanelScreensaverMode NSPanelSettings::NSPanelScreensaverMode_MIN;
constexpr NSPanelSettings_NSPanelScreensaverMode NSPanelSettings::NSPanelScreensaverMode_MAX;
constexpr int NSPanelSettings::NSPanelScreensaverMode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* NSPanelSettings_NSPanelButtonMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protobuf_5fgeneral_2eproto);
  return file_level_enum_descriptors_protobuf_5fgeneral_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t NSPanelSettings_NSPanelButtonMode_internal_data_[] = {
    262144u, 0u, };
bool NSPanelSettings_NSPanelButtonMode_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr NSPanelSettings_NSPanelButtonMode NSPanelSettings::DIRECT_MODE;
constexpr NSPanelSettings_NSPanelButtonMode NSPanelSettings::DETACHED_MODE;
constexpr NSPanelSettings_NSPanelButtonMode NSPanelSettings::CUSTOM_MQTT;
constexpr NSPanelSettings_NSPanelButtonMode NSPanelSettings::FOLLOW_MODE;
constexpr NSPanelSettings_NSPanelButtonMode NSPanelSettings::NSPanelButtonMode_MIN;
constexpr NSPanelSettings_NSPanelButtonMode NSPanelSettings::NSPanelButtonMode_MAX;
constexpr int NSPanelSettings::NSPanelButtonMode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* NSPanelSettings_RelayRegisterType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protobuf_5fgeneral_2eproto);
  return file_level_enum_descriptors_protobuf_5fgeneral_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t NSPanelSettings_RelayRegisterType_internal_data_[] = {
    131072u, 0u, };
bool NSPanelSettings_RelayRegisterType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr NSPanelSettings_RelayRegisterType NSPanelSettings::SWITCH;
constexpr NSPanelSettings_RelayRegisterType NSPanelSettings::LIGHT;
constexpr NSPanelSettings_RelayRegisterType NSPanelSettings::RelayRegisterType_MIN;
constexpr NSPanelSettings_RelayRegisterType NSPanelSettings::RelayRegisterType_MAX;
constexpr int NSPanelSettings::RelayRegisterType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class HomeAssistantEntity::_Internal {
 public:
};

HomeAssistantEntity::HomeAssistantEntity(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:HomeAssistantEntity)
}
inline PROTOBUF_NDEBUG_INLINE HomeAssistantEntity::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::HomeAssistantEntity& from_msg)
      : home_assistant_entity_id_(arena, from.home_assistant_entity_id_),
        _cached_size_{0} {}

HomeAssistantEntity::HomeAssistantEntity(
    ::google::protobuf::Arena* arena,
    const HomeAssistantEntity& from)
    : ::google::protobuf::Message(arena) {
  HomeAssistantEntity* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, can_dim_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, can_dim_),
           offsetof(Impl_, can_rgb_) -
               offsetof(Impl_, can_dim_) +
               sizeof(Impl_::can_rgb_));

  // @@protoc_insertion_point(copy_constructor:HomeAssistantEntity)
}
inline PROTOBUF_NDEBUG_INLINE HomeAssistantEntity::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : home_assistant_entity_id_(arena),
        _cached_size_{0} {}

inline void HomeAssistantEntity::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, can_dim_),
           0,
           offsetof(Impl_, can_rgb_) -
               offsetof(Impl_, can_dim_) +
               sizeof(Impl_::can_rgb_));
}
HomeAssistantEntity::~HomeAssistantEntity() {
  // @@protoc_insertion_point(destructor:HomeAssistantEntity)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HomeAssistantEntity::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.home_assistant_entity_id_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
HomeAssistantEntity::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_._cached_size_),
              false,
          },
          &HomeAssistantEntity::MergeImpl,
          &HomeAssistantEntity::kDescriptorMethods,
          &descriptor_table_protobuf_5fgeneral_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 52, 2> HomeAssistantEntity::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967265,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HomeAssistantEntity_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::HomeAssistantEntity>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool can_color_temperature = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HomeAssistantEntity, _impl_.can_color_temperature_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_color_temperature_)}},
    // bool can_rgb = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HomeAssistantEntity, _impl_.can_rgb_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_rgb_)}},
    // string home_assistant_entity_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.home_assistant_entity_id_)}},
    // bool can_dim = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HomeAssistantEntity, _impl_.can_dim_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_dim_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string home_assistant_entity_id = 2;
    {PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.home_assistant_entity_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool can_dim = 3;
    {PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_dim_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool can_color_temperature = 4;
    {PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_color_temperature_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool can_rgb = 5;
    {PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_rgb_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\23\30\0\0\0\0\0\0"
    "HomeAssistantEntity"
    "home_assistant_entity_id"
  }},
};

PROTOBUF_NOINLINE void HomeAssistantEntity::Clear() {
// @@protoc_insertion_point(message_clear_start:HomeAssistantEntity)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.home_assistant_entity_id_.ClearToEmpty();
  ::memset(&_impl_.can_dim_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.can_rgb_) -
      reinterpret_cast<char*>(&_impl_.can_dim_)) + sizeof(_impl_.can_rgb_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* HomeAssistantEntity::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HomeAssistantEntity)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string home_assistant_entity_id = 2;
  if (!this->_internal_home_assistant_entity_id().empty()) {
    const std::string& _s = this->_internal_home_assistant_entity_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "HomeAssistantEntity.home_assistant_entity_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // bool can_dim = 3;
  if (this->_internal_can_dim() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_can_dim(), target);
  }

  // bool can_color_temperature = 4;
  if (this->_internal_can_color_temperature() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_can_color_temperature(), target);
  }

  // bool can_rgb = 5;
  if (this->_internal_can_rgb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this->_internal_can_rgb(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HomeAssistantEntity)
  return target;
}

::size_t HomeAssistantEntity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HomeAssistantEntity)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string home_assistant_entity_id = 2;
  if (!this->_internal_home_assistant_entity_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_home_assistant_entity_id());
  }

  // bool can_dim = 3;
  if (this->_internal_can_dim() != 0) {
    total_size += 2;
  }

  // bool can_color_temperature = 4;
  if (this->_internal_can_color_temperature() != 0) {
    total_size += 2;
  }

  // bool can_rgb = 5;
  if (this->_internal_can_rgb() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void HomeAssistantEntity::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HomeAssistantEntity*>(&to_msg);
  auto& from = static_cast<const HomeAssistantEntity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HomeAssistantEntity)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_home_assistant_entity_id().empty()) {
    _this->_internal_set_home_assistant_entity_id(from._internal_home_assistant_entity_id());
  }
  if (from._internal_can_dim() != 0) {
    _this->_impl_.can_dim_ = from._impl_.can_dim_;
  }
  if (from._internal_can_color_temperature() != 0) {
    _this->_impl_.can_color_temperature_ = from._impl_.can_color_temperature_;
  }
  if (from._internal_can_rgb() != 0) {
    _this->_impl_.can_rgb_ = from._impl_.can_rgb_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HomeAssistantEntity::CopyFrom(const HomeAssistantEntity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HomeAssistantEntity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HomeAssistantEntity::InternalSwap(HomeAssistantEntity* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.home_assistant_entity_id_, &other->_impl_.home_assistant_entity_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_rgb_)
      + sizeof(HomeAssistantEntity::_impl_.can_rgb_)
      - PROTOBUF_FIELD_OFFSET(HomeAssistantEntity, _impl_.can_dim_)>(
          reinterpret_cast<char*>(&_impl_.can_dim_),
          reinterpret_cast<char*>(&other->_impl_.can_dim_));
}

::google::protobuf::Metadata HomeAssistantEntity::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OpenhabLightEntity::_Internal {
 public:
};

OpenhabLightEntity::OpenhabLightEntity(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:OpenhabLightEntity)
}
inline PROTOBUF_NDEBUG_INLINE OpenhabLightEntity::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::OpenhabLightEntity& from_msg)
      : openhab_id_(arena, from.openhab_id_),
        openhab_dim_channel_(arena, from.openhab_dim_channel_),
        openhab_color_temperature_channel_(arena, from.openhab_color_temperature_channel_),
        openhab_rgb_channel_(arena, from.openhab_rgb_channel_),
        _cached_size_{0} {}

OpenhabLightEntity::OpenhabLightEntity(
    ::google::protobuf::Arena* arena,
    const OpenhabLightEntity& from)
    : ::google::protobuf::Message(arena) {
  OpenhabLightEntity* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, can_dim_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, can_dim_),
           offsetof(Impl_, can_rgb_) -
               offsetof(Impl_, can_dim_) +
               sizeof(Impl_::can_rgb_));

  // @@protoc_insertion_point(copy_constructor:OpenhabLightEntity)
}
inline PROTOBUF_NDEBUG_INLINE OpenhabLightEntity::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : openhab_id_(arena),
        openhab_dim_channel_(arena),
        openhab_color_temperature_channel_(arena),
        openhab_rgb_channel_(arena),
        _cached_size_{0} {}

inline void OpenhabLightEntity::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, can_dim_),
           0,
           offsetof(Impl_, can_rgb_) -
               offsetof(Impl_, can_dim_) +
               sizeof(Impl_::can_rgb_));
}
OpenhabLightEntity::~OpenhabLightEntity() {
  // @@protoc_insertion_point(destructor:OpenhabLightEntity)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void OpenhabLightEntity::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.openhab_id_.Destroy();
  _impl_.openhab_dim_channel_.Destroy();
  _impl_.openhab_color_temperature_channel_.Destroy();
  _impl_.openhab_rgb_channel_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
OpenhabLightEntity::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_._cached_size_),
              false,
          },
          &OpenhabLightEntity::MergeImpl,
          &OpenhabLightEntity::kDescriptorMethods,
          &descriptor_table_protobuf_5fgeneral_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 108, 2> OpenhabLightEntity::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_OpenhabLightEntity_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::OpenhabLightEntity>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string openhab_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_id_)}},
    // string openhab_dim_channel = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_dim_channel_)}},
    // string openhab_color_temperature_channel = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_color_temperature_channel_)}},
    // string openhab_rgb_channel = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_rgb_channel_)}},
    // bool can_dim = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(OpenhabLightEntity, _impl_.can_dim_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_dim_)}},
    // bool can_color_temperature = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(OpenhabLightEntity, _impl_.can_color_temperature_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_color_temperature_)}},
    // bool can_rgb = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(OpenhabLightEntity, _impl_.can_rgb_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_rgb_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string openhab_id = 1;
    {PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string openhab_dim_channel = 2;
    {PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_dim_channel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string openhab_color_temperature_channel = 3;
    {PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_color_temperature_channel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string openhab_rgb_channel = 4;
    {PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.openhab_rgb_channel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool can_dim = 5;
    {PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_dim_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool can_color_temperature = 6;
    {PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_color_temperature_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool can_rgb = 7;
    {PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_rgb_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\22\12\23\41\23\0\0\0"
    "OpenhabLightEntity"
    "openhab_id"
    "openhab_dim_channel"
    "openhab_color_temperature_channel"
    "openhab_rgb_channel"
  }},
};

PROTOBUF_NOINLINE void OpenhabLightEntity::Clear() {
// @@protoc_insertion_point(message_clear_start:OpenhabLightEntity)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.openhab_id_.ClearToEmpty();
  _impl_.openhab_dim_channel_.ClearToEmpty();
  _impl_.openhab_color_temperature_channel_.ClearToEmpty();
  _impl_.openhab_rgb_channel_.ClearToEmpty();
  ::memset(&_impl_.can_dim_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.can_rgb_) -
      reinterpret_cast<char*>(&_impl_.can_dim_)) + sizeof(_impl_.can_rgb_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* OpenhabLightEntity::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:OpenhabLightEntity)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string openhab_id = 1;
  if (!this->_internal_openhab_id().empty()) {
    const std::string& _s = this->_internal_openhab_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "OpenhabLightEntity.openhab_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string openhab_dim_channel = 2;
  if (!this->_internal_openhab_dim_channel().empty()) {
    const std::string& _s = this->_internal_openhab_dim_channel();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "OpenhabLightEntity.openhab_dim_channel");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string openhab_color_temperature_channel = 3;
  if (!this->_internal_openhab_color_temperature_channel().empty()) {
    const std::string& _s = this->_internal_openhab_color_temperature_channel();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "OpenhabLightEntity.openhab_color_temperature_channel");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string openhab_rgb_channel = 4;
  if (!this->_internal_openhab_rgb_channel().empty()) {
    const std::string& _s = this->_internal_openhab_rgb_channel();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "OpenhabLightEntity.openhab_rgb_channel");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // bool can_dim = 5;
  if (this->_internal_can_dim() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this->_internal_can_dim(), target);
  }

  // bool can_color_temperature = 6;
  if (this->_internal_can_color_temperature() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        6, this->_internal_can_color_temperature(), target);
  }

  // bool can_rgb = 7;
  if (this->_internal_can_rgb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        7, this->_internal_can_rgb(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OpenhabLightEntity)
  return target;
}

::size_t OpenhabLightEntity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OpenhabLightEntity)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string openhab_id = 1;
  if (!this->_internal_openhab_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_openhab_id());
  }

  // string openhab_dim_channel = 2;
  if (!this->_internal_openhab_dim_channel().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_openhab_dim_channel());
  }

  // string openhab_color_temperature_channel = 3;
  if (!this->_internal_openhab_color_temperature_channel().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_openhab_color_temperature_channel());
  }

  // string openhab_rgb_channel = 4;
  if (!this->_internal_openhab_rgb_channel().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_openhab_rgb_channel());
  }

  // bool can_dim = 5;
  if (this->_internal_can_dim() != 0) {
    total_size += 2;
  }

  // bool can_color_temperature = 6;
  if (this->_internal_can_color_temperature() != 0) {
    total_size += 2;
  }

  // bool can_rgb = 7;
  if (this->_internal_can_rgb() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void OpenhabLightEntity::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OpenhabLightEntity*>(&to_msg);
  auto& from = static_cast<const OpenhabLightEntity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:OpenhabLightEntity)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_openhab_id().empty()) {
    _this->_internal_set_openhab_id(from._internal_openhab_id());
  }
  if (!from._internal_openhab_dim_channel().empty()) {
    _this->_internal_set_openhab_dim_channel(from._internal_openhab_dim_channel());
  }
  if (!from._internal_openhab_color_temperature_channel().empty()) {
    _this->_internal_set_openhab_color_temperature_channel(from._internal_openhab_color_temperature_channel());
  }
  if (!from._internal_openhab_rgb_channel().empty()) {
    _this->_internal_set_openhab_rgb_channel(from._internal_openhab_rgb_channel());
  }
  if (from._internal_can_dim() != 0) {
    _this->_impl_.can_dim_ = from._impl_.can_dim_;
  }
  if (from._internal_can_color_temperature() != 0) {
    _this->_impl_.can_color_temperature_ = from._impl_.can_color_temperature_;
  }
  if (from._internal_can_rgb() != 0) {
    _this->_impl_.can_rgb_ = from._impl_.can_rgb_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OpenhabLightEntity::CopyFrom(const OpenhabLightEntity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OpenhabLightEntity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OpenhabLightEntity::InternalSwap(OpenhabLightEntity* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.openhab_id_, &other->_impl_.openhab_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.openhab_dim_channel_, &other->_impl_.openhab_dim_channel_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.openhab_color_temperature_channel_, &other->_impl_.openhab_color_temperature_channel_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.openhab_rgb_channel_, &other->_impl_.openhab_rgb_channel_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_rgb_)
      + sizeof(OpenhabLightEntity::_impl_.can_rgb_)
      - PROTOBUF_FIELD_OFFSET(OpenhabLightEntity, _impl_.can_dim_)>(
          reinterpret_cast<char*>(&_impl_.can_dim_),
          reinterpret_cast<char*>(&other->_impl_.can_dim_));
}

::google::protobuf::Metadata OpenhabLightEntity::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NSPanelSettings::_Internal {
 public:
  using HasBits =
      decltype(std::declval<NSPanelSettings>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_._has_bits_);
};

NSPanelSettings::NSPanelSettings(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NSPanelSettings)
}
inline PROTOBUF_NDEBUG_INLINE NSPanelSettings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NSPanelSettings& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        rooms_{visibility, arena, from.rooms_},
        _rooms_cached_byte_size_{0},
        scenes_{visibility, arena, from.scenes_},
        _scenes_cached_byte_size_{0},
        mac_address_(arena, from.mac_address_),
        name_(arena, from.name_),
        button1_mqtt_topic_(arena, from.button1_mqtt_topic_),
        button2_mqtt_topic_(arena, from.button2_mqtt_topic_),
        button1_mqtt_payload_(arena, from.button1_mqtt_payload_),
        button2_mqtt_payload_(arena, from.button2_mqtt_payload_),
        ip_address_(arena, from.ip_address_) {}

NSPanelSettings::NSPanelSettings(
    ::google::protobuf::Arena* arena,
    const NSPanelSettings& from)
    : ::google::protobuf::Message(arena) {
  NSPanelSettings* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, relay2_register_type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::relay2_register_type_));

  // @@protoc_insertion_point(copy_constructor:NSPanelSettings)
}
inline PROTOBUF_NDEBUG_INLINE NSPanelSettings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        rooms_{visibility, arena},
        _rooms_cached_byte_size_{0},
        scenes_{visibility, arena},
        _scenes_cached_byte_size_{0},
        mac_address_(arena),
        name_(arena),
        button1_mqtt_topic_(arena),
        button2_mqtt_topic_(arena),
        button1_mqtt_payload_(arena),
        button2_mqtt_payload_(arena),
        ip_address_(arena) {}

inline void NSPanelSettings::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, relay2_register_type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::relay2_register_type_));
}
NSPanelSettings::~NSPanelSettings() {
  // @@protoc_insertion_point(destructor:NSPanelSettings)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NSPanelSettings::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.mac_address_.Destroy();
  _impl_.name_.Destroy();
  _impl_.button1_mqtt_topic_.Destroy();
  _impl_.button2_mqtt_topic_.Destroy();
  _impl_.button1_mqtt_payload_.Destroy();
  _impl_.button2_mqtt_payload_.Destroy();
  _impl_.ip_address_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NSPanelSettings::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_._cached_size_),
              false,
          },
          &NSPanelSettings::MergeImpl,
          &NSPanelSettings::kDescriptorMethods,
          &descriptor_table_protobuf_5fgeneral_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 41, 0, 165, 9> NSPanelSettings::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_._has_bits_),
    0, // no _extensions_
    51, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    0,  // skipmap
    offsetof(decltype(_table_), field_entries),
    41,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NSPanelSettings_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NSPanelSettings>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.id_), 4>(),
     {8, 4, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.id_)}},
    // string mac_address = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.mac_address_)}},
    // string name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.name_)}},
    // int32 home = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.home_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.home_)}},
    // .NSPanelSettings.NSPanelDefaultPage default_page = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.default_page_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.default_page_)}},
    // int32 raise_to_100_light_level = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.raise_to_100_light_level_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.raise_to_100_light_level_)}},
    // int32 color_temp_min = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.color_temp_min_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.color_temp_min_)}},
    // int32 color_temp_max = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.color_temp_max_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.color_temp_max_)}},
    // bool reverse_color_temp = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NSPanelSettings, _impl_.reverse_color_temp_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.reverse_color_temp_)}},
    // int32 min_button_push_time = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.min_button_push_time_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.min_button_push_time_)}},
    // int32 button_long_press_time = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.button_long_press_time_), 63>(),
     {88, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button_long_press_time_)}},
    // int32 special_mode_trigger_time = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.special_mode_trigger_time_), 63>(),
     {96, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.special_mode_trigger_time_)}},
    // int32 special_mode_release_time = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.special_mode_release_time_), 63>(),
     {104, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.special_mode_release_time_)}},
    // int32 mqtt_ignore_time = 14;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.mqtt_ignore_time_), 63>(),
     {112, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.mqtt_ignore_time_)}},
    // int32 screen_dim_level = 15;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelSettings, _impl_.screen_dim_level_), 63>(),
     {120, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screen_dim_level_)}},
    // int32 screensaver_dim_level = 16;
    {::_pbi::TcParser::FastV32S2,
     {384, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screensaver_dim_level_)}},
    // int32 screensaver_activation_timeout = 17;
    {::_pbi::TcParser::FastV32S2,
     {392, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screensaver_activation_timeout_)}},
    // .NSPanelSettings.NSPanelScreensaverMode screensaver_mode = 18;
    {::_pbi::TcParser::FastV32S2,
     {400, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screensaver_mode_)}},
    // .time_format clock_format = 19;
    {::_pbi::TcParser::FastV32S2,
     {408, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.clock_format_)}},
    // .temperature_format temperature_unit = 20;
    {::_pbi::TcParser::FastV32S2,
     {416, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.temperature_unit_)}},
    // bool is_us_panel = 21;
    {::_pbi::TcParser::FastV8S2,
     {424, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.is_us_panel_)}},
    // bool lock_to_default_room = 22;
    {::_pbi::TcParser::FastV8S2,
     {432, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.lock_to_default_room_)}},
    // bool reverse_relays = 23;
    {::_pbi::TcParser::FastV8S2,
     {440, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.reverse_relays_)}},
    // bool relay1_default_mode = 24;
    {::_pbi::TcParser::FastV8S2,
     {448, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.relay1_default_mode_)}},
    // bool relay2_default_mode = 25;
    {::_pbi::TcParser::FastV8S2,
     {456, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.relay2_default_mode_)}},
    // int32 temperature_calibration = 26;
    {::_pbi::TcParser::FastV32S2,
     {464, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.temperature_calibration_)}},
    // .NSPanelSettings.NSPanelButtonMode button1_mode = 27;
    {::_pbi::TcParser::FastV32S2,
     {472, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button1_mode_)}},
    // .NSPanelSettings.NSPanelButtonMode button2_mode = 28;
    {::_pbi::TcParser::FastV32S2,
     {480, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button2_mode_)}},
    // optional string button1_mqtt_topic = 29;
    {::_pbi::TcParser::FastUS2,
     {490, 0, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button1_mqtt_topic_)}},
    // optional string button2_mqtt_topic = 30;
    {::_pbi::TcParser::FastUS2,
     {498, 1, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button2_mqtt_topic_)}},
    // optional string button1_mqtt_payload = 31;
    {::_pbi::TcParser::FastUS2,
     {506, 2, 0, PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button1_mqtt_payload_)}},
  }}, {{
    33, 0, 2,
    4092, 32, 65528, 38,
    65535, 65535
  }}, {{
    // optional int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.id_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string mac_address = 2;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.mac_address_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string name = 3;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 home = 4;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.home_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .NSPanelSettings.NSPanelDefaultPage default_page = 5;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.default_page_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 raise_to_100_light_level = 6;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.raise_to_100_light_level_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 color_temp_min = 7;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.color_temp_min_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 color_temp_max = 8;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.color_temp_max_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool reverse_color_temp = 9;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.reverse_color_temp_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 min_button_push_time = 10;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.min_button_push_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 button_long_press_time = 11;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button_long_press_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 special_mode_trigger_time = 12;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.special_mode_trigger_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 special_mode_release_time = 13;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.special_mode_release_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 mqtt_ignore_time = 14;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.mqtt_ignore_time_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 screen_dim_level = 15;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screen_dim_level_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 screensaver_dim_level = 16;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screensaver_dim_level_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 screensaver_activation_timeout = 17;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screensaver_activation_timeout_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .NSPanelSettings.NSPanelScreensaverMode screensaver_mode = 18;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.screensaver_mode_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .time_format clock_format = 19;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.clock_format_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .temperature_format temperature_unit = 20;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.temperature_unit_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // bool is_us_panel = 21;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.is_us_panel_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool lock_to_default_room = 22;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.lock_to_default_room_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool reverse_relays = 23;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.reverse_relays_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool relay1_default_mode = 24;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.relay1_default_mode_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool relay2_default_mode = 25;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.relay2_default_mode_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 temperature_calibration = 26;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.temperature_calibration_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .NSPanelSettings.NSPanelButtonMode button1_mode = 27;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button1_mode_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .NSPanelSettings.NSPanelButtonMode button2_mode = 28;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button2_mode_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // optional string button1_mqtt_topic = 29;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button1_mqtt_topic_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string button2_mqtt_topic = 30;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button2_mqtt_topic_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string button1_mqtt_payload = 31;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button1_mqtt_payload_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string button2_mqtt_payload = 32;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button2_mqtt_payload_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 button1_detached_light_id = 33;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button1_detached_light_id_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 button2_detached_light_id = 34;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.button2_detached_light_id_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bool denied = 45;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.denied_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool accepted = 46;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.accepted_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // repeated int32 rooms = 47;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.rooms_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated int32 scenes = 48;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.scenes_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // string ip_address = 49;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.ip_address_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .NSPanelSettings.RelayRegisterType relay1_register_type = 50;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.relay1_register_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .NSPanelSettings.RelayRegisterType relay2_register_type = 51;
    {PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.relay2_register_type_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\17\0\13\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\22\22\24\24\0\0\0\0\0\0\12\0\0\0\0\0\0\0\0"
    "NSPanelSettings"
    "mac_address"
    "name"
    "button1_mqtt_topic"
    "button2_mqtt_topic"
    "button1_mqtt_payload"
    "button2_mqtt_payload"
    "ip_address"
  }},
};

PROTOBUF_NOINLINE void NSPanelSettings::Clear() {
// @@protoc_insertion_point(message_clear_start:NSPanelSettings)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rooms_.Clear();
  _impl_.scenes_.Clear();
  _impl_.mac_address_.ClearToEmpty();
  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.button1_mqtt_topic_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.button2_mqtt_topic_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.button1_mqtt_payload_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.button2_mqtt_payload_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.ip_address_.ClearToEmpty();
  _impl_.id_ = 0;
  ::memset(&_impl_.home_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.button2_mode_) -
      reinterpret_cast<char*>(&_impl_.home_)) + sizeof(_impl_.button2_mode_));
  if (cached_has_bits & 0x00000060u) {
    ::memset(&_impl_.button1_detached_light_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.button2_detached_light_id_) -
        reinterpret_cast<char*>(&_impl_.button1_detached_light_id_)) + sizeof(_impl_.button2_detached_light_id_));
  }
  ::memset(&_impl_.relay1_default_mode_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.relay2_register_type_) -
      reinterpret_cast<char*>(&_impl_.relay1_default_mode_)) + sizeof(_impl_.relay2_register_type_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* NSPanelSettings::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NSPanelSettings)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 id = 1;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string mac_address = 2;
  if (!this->_internal_mac_address().empty()) {
    const std::string& _s = this->_internal_mac_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelSettings.mac_address");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelSettings.name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 home = 4;
  if (this->_internal_home() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_home(), target);
  }

  // .NSPanelSettings.NSPanelDefaultPage default_page = 5;
  if (this->_internal_default_page() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        5, this->_internal_default_page(), target);
  }

  // int32 raise_to_100_light_level = 6;
  if (this->_internal_raise_to_100_light_level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<6>(
            stream, this->_internal_raise_to_100_light_level(), target);
  }

  // int32 color_temp_min = 7;
  if (this->_internal_color_temp_min() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<7>(
            stream, this->_internal_color_temp_min(), target);
  }

  // int32 color_temp_max = 8;
  if (this->_internal_color_temp_max() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<8>(
            stream, this->_internal_color_temp_max(), target);
  }

  // bool reverse_color_temp = 9;
  if (this->_internal_reverse_color_temp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        9, this->_internal_reverse_color_temp(), target);
  }

  // int32 min_button_push_time = 10;
  if (this->_internal_min_button_push_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<10>(
            stream, this->_internal_min_button_push_time(), target);
  }

  // int32 button_long_press_time = 11;
  if (this->_internal_button_long_press_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<11>(
            stream, this->_internal_button_long_press_time(), target);
  }

  // int32 special_mode_trigger_time = 12;
  if (this->_internal_special_mode_trigger_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<12>(
            stream, this->_internal_special_mode_trigger_time(), target);
  }

  // int32 special_mode_release_time = 13;
  if (this->_internal_special_mode_release_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<13>(
            stream, this->_internal_special_mode_release_time(), target);
  }

  // int32 mqtt_ignore_time = 14;
  if (this->_internal_mqtt_ignore_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<14>(
            stream, this->_internal_mqtt_ignore_time(), target);
  }

  // int32 screen_dim_level = 15;
  if (this->_internal_screen_dim_level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<15>(
            stream, this->_internal_screen_dim_level(), target);
  }

  // int32 screensaver_dim_level = 16;
  if (this->_internal_screensaver_dim_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        16, this->_internal_screensaver_dim_level(), target);
  }

  // int32 screensaver_activation_timeout = 17;
  if (this->_internal_screensaver_activation_timeout() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        17, this->_internal_screensaver_activation_timeout(), target);
  }

  // .NSPanelSettings.NSPanelScreensaverMode screensaver_mode = 18;
  if (this->_internal_screensaver_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        18, this->_internal_screensaver_mode(), target);
  }

  // .time_format clock_format = 19;
  if (this->_internal_clock_format() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        19, this->_internal_clock_format(), target);
  }

  // .temperature_format temperature_unit = 20;
  if (this->_internal_temperature_unit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        20, this->_internal_temperature_unit(), target);
  }

  // bool is_us_panel = 21;
  if (this->_internal_is_us_panel() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        21, this->_internal_is_us_panel(), target);
  }

  // bool lock_to_default_room = 22;
  if (this->_internal_lock_to_default_room() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        22, this->_internal_lock_to_default_room(), target);
  }

  // bool reverse_relays = 23;
  if (this->_internal_reverse_relays() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        23, this->_internal_reverse_relays(), target);
  }

  // bool relay1_default_mode = 24;
  if (this->_internal_relay1_default_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        24, this->_internal_relay1_default_mode(), target);
  }

  // bool relay2_default_mode = 25;
  if (this->_internal_relay2_default_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        25, this->_internal_relay2_default_mode(), target);
  }

  // int32 temperature_calibration = 26;
  if (this->_internal_temperature_calibration() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        26, this->_internal_temperature_calibration(), target);
  }

  // .NSPanelSettings.NSPanelButtonMode button1_mode = 27;
  if (this->_internal_button1_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        27, this->_internal_button1_mode(), target);
  }

  // .NSPanelSettings.NSPanelButtonMode button2_mode = 28;
  if (this->_internal_button2_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        28, this->_internal_button2_mode(), target);
  }

  // optional string button1_mqtt_topic = 29;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_button1_mqtt_topic();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelSettings.button1_mqtt_topic");
    target = stream->WriteStringMaybeAliased(29, _s, target);
  }

  // optional string button2_mqtt_topic = 30;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_button2_mqtt_topic();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelSettings.button2_mqtt_topic");
    target = stream->WriteStringMaybeAliased(30, _s, target);
  }

  // optional string button1_mqtt_payload = 31;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_button1_mqtt_payload();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelSettings.button1_mqtt_payload");
    target = stream->WriteStringMaybeAliased(31, _s, target);
  }

  // optional string button2_mqtt_payload = 32;
  if (cached_has_bits & 0x00000008u) {
    const std::string& _s = this->_internal_button2_mqtt_payload();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelSettings.button2_mqtt_payload");
    target = stream->WriteStringMaybeAliased(32, _s, target);
  }

  // optional int32 button1_detached_light_id = 33;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        33, this->_internal_button1_detached_light_id(), target);
  }

  // optional int32 button2_detached_light_id = 34;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        34, this->_internal_button2_detached_light_id(), target);
  }

  // bool denied = 45;
  if (this->_internal_denied() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        45, this->_internal_denied(), target);
  }

  // bool accepted = 46;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        46, this->_internal_accepted(), target);
  }

  // repeated int32 rooms = 47;
  {
    int byte_size = _impl_._rooms_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          47, _internal_rooms(), byte_size, target);
    }
  }

  // repeated int32 scenes = 48;
  {
    int byte_size = _impl_._scenes_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          48, _internal_scenes(), byte_size, target);
    }
  }

  // string ip_address = 49;
  if (!this->_internal_ip_address().empty()) {
    const std::string& _s = this->_internal_ip_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelSettings.ip_address");
    target = stream->WriteStringMaybeAliased(49, _s, target);
  }

  // .NSPanelSettings.RelayRegisterType relay1_register_type = 50;
  if (this->_internal_relay1_register_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        50, this->_internal_relay1_register_type(), target);
  }

  // .NSPanelSettings.RelayRegisterType relay2_register_type = 51;
  if (this->_internal_relay2_register_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        51, this->_internal_relay2_register_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NSPanelSettings)
  return target;
}

::size_t NSPanelSettings::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NSPanelSettings)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated int32 rooms = 47;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_rooms())
    ;
    _impl_._rooms_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated int32 scenes = 48;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(
        this->_internal_scenes())
    ;
    _impl_._scenes_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 2 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // string mac_address = 2;
  if (!this->_internal_mac_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_mac_address());
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string button1_mqtt_topic = 29;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_button1_mqtt_topic());
    }

    // optional string button2_mqtt_topic = 30;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_button2_mqtt_topic());
    }

    // optional string button1_mqtt_payload = 31;
    if (cached_has_bits & 0x00000004u) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_button1_mqtt_payload());
    }

    // optional string button2_mqtt_payload = 32;
    if (cached_has_bits & 0x00000008u) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_button2_mqtt_payload());
    }

  }
  // string ip_address = 49;
  if (!this->_internal_ip_address().empty()) {
    total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_ip_address());
  }

  // optional int32 id = 1;
  if (cached_has_bits & 0x00000010u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  // int32 home = 4;
  if (this->_internal_home() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_home());
  }

  // .NSPanelSettings.NSPanelDefaultPage default_page = 5;
  if (this->_internal_default_page() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_default_page());
  }

  // int32 raise_to_100_light_level = 6;
  if (this->_internal_raise_to_100_light_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_raise_to_100_light_level());
  }

  // int32 color_temp_min = 7;
  if (this->_internal_color_temp_min() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_color_temp_min());
  }

  // int32 color_temp_max = 8;
  if (this->_internal_color_temp_max() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_color_temp_max());
  }

  // int32 min_button_push_time = 10;
  if (this->_internal_min_button_push_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_min_button_push_time());
  }

  // int32 button_long_press_time = 11;
  if (this->_internal_button_long_press_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_button_long_press_time());
  }

  // int32 special_mode_trigger_time = 12;
  if (this->_internal_special_mode_trigger_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_special_mode_trigger_time());
  }

  // int32 special_mode_release_time = 13;
  if (this->_internal_special_mode_release_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_special_mode_release_time());
  }

  // int32 mqtt_ignore_time = 14;
  if (this->_internal_mqtt_ignore_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_mqtt_ignore_time());
  }

  // int32 screen_dim_level = 15;
  if (this->_internal_screen_dim_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_screen_dim_level());
  }

  // int32 screensaver_dim_level = 16;
  if (this->_internal_screensaver_dim_level() != 0) {
    total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                    this->_internal_screensaver_dim_level());
  }

  // int32 screensaver_activation_timeout = 17;
  if (this->_internal_screensaver_activation_timeout() != 0) {
    total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                    this->_internal_screensaver_activation_timeout());
  }

  // .NSPanelSettings.NSPanelScreensaverMode screensaver_mode = 18;
  if (this->_internal_screensaver_mode() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_screensaver_mode());
  }

  // bool reverse_color_temp = 9;
  if (this->_internal_reverse_color_temp() != 0) {
    total_size += 2;
  }

  // bool is_us_panel = 21;
  if (this->_internal_is_us_panel() != 0) {
    total_size += 3;
  }

  // bool lock_to_default_room = 22;
  if (this->_internal_lock_to_default_room() != 0) {
    total_size += 3;
  }

  // bool reverse_relays = 23;
  if (this->_internal_reverse_relays() != 0) {
    total_size += 3;
  }

  // .time_format clock_format = 19;
  if (this->_internal_clock_format() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_clock_format());
  }

  // .temperature_format temperature_unit = 20;
  if (this->_internal_temperature_unit() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_temperature_unit());
  }

  // int32 temperature_calibration = 26;
  if (this->_internal_temperature_calibration() != 0) {
    total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                    this->_internal_temperature_calibration());
  }

  // .NSPanelSettings.NSPanelButtonMode button1_mode = 27;
  if (this->_internal_button1_mode() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_button1_mode());
  }

  // .NSPanelSettings.NSPanelButtonMode button2_mode = 28;
  if (this->_internal_button2_mode() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_button2_mode());
  }

  if (cached_has_bits & 0x00000060u) {
    // optional int32 button1_detached_light_id = 33;
    if (cached_has_bits & 0x00000020u) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this->_internal_button1_detached_light_id());
    }

    // optional int32 button2_detached_light_id = 34;
    if (cached_has_bits & 0x00000040u) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this->_internal_button2_detached_light_id());
    }

  }
  // bool relay1_default_mode = 24;
  if (this->_internal_relay1_default_mode() != 0) {
    total_size += 3;
  }

  // bool relay2_default_mode = 25;
  if (this->_internal_relay2_default_mode() != 0) {
    total_size += 3;
  }

  // bool denied = 45;
  if (this->_internal_denied() != 0) {
    total_size += 3;
  }

  // bool accepted = 46;
  if (this->_internal_accepted() != 0) {
    total_size += 3;
  }

  // .NSPanelSettings.RelayRegisterType relay1_register_type = 50;
  if (this->_internal_relay1_register_type() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_relay1_register_type());
  }

  // .NSPanelSettings.RelayRegisterType relay2_register_type = 51;
  if (this->_internal_relay2_register_type() != 0) {
    total_size += 2 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_relay2_register_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NSPanelSettings::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NSPanelSettings*>(&to_msg);
  auto& from = static_cast<const NSPanelSettings&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NSPanelSettings)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_rooms()->MergeFrom(from._internal_rooms());
  _this->_internal_mutable_scenes()->MergeFrom(from._internal_scenes());
  if (!from._internal_mac_address().empty()) {
    _this->_internal_set_mac_address(from._internal_mac_address());
  }
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_button1_mqtt_topic(from._internal_button1_mqtt_topic());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_button2_mqtt_topic(from._internal_button2_mqtt_topic());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_button1_mqtt_payload(from._internal_button1_mqtt_payload());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_button2_mqtt_payload(from._internal_button2_mqtt_payload());
    }
  }
  if (!from._internal_ip_address().empty()) {
    _this->_internal_set_ip_address(from._internal_ip_address());
  }
  if (cached_has_bits & 0x00000010u) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_home() != 0) {
    _this->_impl_.home_ = from._impl_.home_;
  }
  if (from._internal_default_page() != 0) {
    _this->_impl_.default_page_ = from._impl_.default_page_;
  }
  if (from._internal_raise_to_100_light_level() != 0) {
    _this->_impl_.raise_to_100_light_level_ = from._impl_.raise_to_100_light_level_;
  }
  if (from._internal_color_temp_min() != 0) {
    _this->_impl_.color_temp_min_ = from._impl_.color_temp_min_;
  }
  if (from._internal_color_temp_max() != 0) {
    _this->_impl_.color_temp_max_ = from._impl_.color_temp_max_;
  }
  if (from._internal_min_button_push_time() != 0) {
    _this->_impl_.min_button_push_time_ = from._impl_.min_button_push_time_;
  }
  if (from._internal_button_long_press_time() != 0) {
    _this->_impl_.button_long_press_time_ = from._impl_.button_long_press_time_;
  }
  if (from._internal_special_mode_trigger_time() != 0) {
    _this->_impl_.special_mode_trigger_time_ = from._impl_.special_mode_trigger_time_;
  }
  if (from._internal_special_mode_release_time() != 0) {
    _this->_impl_.special_mode_release_time_ = from._impl_.special_mode_release_time_;
  }
  if (from._internal_mqtt_ignore_time() != 0) {
    _this->_impl_.mqtt_ignore_time_ = from._impl_.mqtt_ignore_time_;
  }
  if (from._internal_screen_dim_level() != 0) {
    _this->_impl_.screen_dim_level_ = from._impl_.screen_dim_level_;
  }
  if (from._internal_screensaver_dim_level() != 0) {
    _this->_impl_.screensaver_dim_level_ = from._impl_.screensaver_dim_level_;
  }
  if (from._internal_screensaver_activation_timeout() != 0) {
    _this->_impl_.screensaver_activation_timeout_ = from._impl_.screensaver_activation_timeout_;
  }
  if (from._internal_screensaver_mode() != 0) {
    _this->_impl_.screensaver_mode_ = from._impl_.screensaver_mode_;
  }
  if (from._internal_reverse_color_temp() != 0) {
    _this->_impl_.reverse_color_temp_ = from._impl_.reverse_color_temp_;
  }
  if (from._internal_is_us_panel() != 0) {
    _this->_impl_.is_us_panel_ = from._impl_.is_us_panel_;
  }
  if (from._internal_lock_to_default_room() != 0) {
    _this->_impl_.lock_to_default_room_ = from._impl_.lock_to_default_room_;
  }
  if (from._internal_reverse_relays() != 0) {
    _this->_impl_.reverse_relays_ = from._impl_.reverse_relays_;
  }
  if (from._internal_clock_format() != 0) {
    _this->_impl_.clock_format_ = from._impl_.clock_format_;
  }
  if (from._internal_temperature_unit() != 0) {
    _this->_impl_.temperature_unit_ = from._impl_.temperature_unit_;
  }
  if (from._internal_temperature_calibration() != 0) {
    _this->_impl_.temperature_calibration_ = from._impl_.temperature_calibration_;
  }
  if (from._internal_button1_mode() != 0) {
    _this->_impl_.button1_mode_ = from._impl_.button1_mode_;
  }
  if (from._internal_button2_mode() != 0) {
    _this->_impl_.button2_mode_ = from._impl_.button2_mode_;
  }
  if (cached_has_bits & 0x00000060u) {
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.button1_detached_light_id_ = from._impl_.button1_detached_light_id_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.button2_detached_light_id_ = from._impl_.button2_detached_light_id_;
    }
  }
  if (from._internal_relay1_default_mode() != 0) {
    _this->_impl_.relay1_default_mode_ = from._impl_.relay1_default_mode_;
  }
  if (from._internal_relay2_default_mode() != 0) {
    _this->_impl_.relay2_default_mode_ = from._impl_.relay2_default_mode_;
  }
  if (from._internal_denied() != 0) {
    _this->_impl_.denied_ = from._impl_.denied_;
  }
  if (from._internal_accepted() != 0) {
    _this->_impl_.accepted_ = from._impl_.accepted_;
  }
  if (from._internal_relay1_register_type() != 0) {
    _this->_impl_.relay1_register_type_ = from._impl_.relay1_register_type_;
  }
  if (from._internal_relay2_register_type() != 0) {
    _this->_impl_.relay2_register_type_ = from._impl_.relay2_register_type_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NSPanelSettings::CopyFrom(const NSPanelSettings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NSPanelSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NSPanelSettings::InternalSwap(NSPanelSettings* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.rooms_.InternalSwap(&other->_impl_.rooms_);
  _impl_.scenes_.InternalSwap(&other->_impl_.scenes_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mac_address_, &other->_impl_.mac_address_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.button1_mqtt_topic_, &other->_impl_.button1_mqtt_topic_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.button2_mqtt_topic_, &other->_impl_.button2_mqtt_topic_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.button1_mqtt_payload_, &other->_impl_.button1_mqtt_payload_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.button2_mqtt_payload_, &other->_impl_.button2_mqtt_payload_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_address_, &other->_impl_.ip_address_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.relay2_register_type_)
      + sizeof(NSPanelSettings::_impl_.relay2_register_type_)
      - PROTOBUF_FIELD_OFFSET(NSPanelSettings, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata NSPanelSettings::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_protobuf_5fgeneral_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
