// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf_nspanel_entity.proto
// Protobuf C++ Version: 5.27.0

#include "protobuf_nspanel_entity.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr NSPanelEntityState_Light::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        light_id_{0},
        brightness_{0},
        color_temp_{0},
        hue_{0},
        saturation_{0},
        can_color_temp_{false},
        can_color_{false},
        current_light_mode_{static_cast< ::NSPanelEntityState_Light_LightMode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NSPanelEntityState_Light::NSPanelEntityState_Light(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NSPanelEntityState_LightDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NSPanelEntityState_LightDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NSPanelEntityState_LightDefaultTypeInternal() {}
  union {
    NSPanelEntityState_Light _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NSPanelEntityState_LightDefaultTypeInternal _NSPanelEntityState_Light_default_instance_;

inline constexpr NSPanelEntityState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : entity_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR NSPanelEntityState::NSPanelEntityState(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NSPanelEntityStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NSPanelEntityStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NSPanelEntityStateDefaultTypeInternal() {}
  union {
    NSPanelEntityState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NSPanelEntityStateDefaultTypeInternal _NSPanelEntityState_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_protobuf_5fnspanel_5fentity_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protobuf_5fnspanel_5fentity_2eproto = nullptr;
const ::uint32_t
    TableStruct_protobuf_5fnspanel_5fentity_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.light_id_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.brightness_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.color_temp_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.hue_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.saturation_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.can_color_temp_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.can_color_),
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState_Light, _impl_.current_light_mode_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::NSPanelEntityState, _impl_.entity_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::NSPanelEntityState_Light)},
        {17, -1, -1, sizeof(::NSPanelEntityState)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_NSPanelEntityState_Light_default_instance_._instance,
    &::_NSPanelEntityState_default_instance_._instance,
};
const char descriptor_table_protodef_protobuf_5fnspanel_5fentity_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\035protobuf_nspanel_entity.proto\"\317\002\n\022NSPa"
    "nelEntityState\022*\n\005light\030\001 \001(\0132\031.NSPanelE"
    "ntityState.LightH\000\032\202\002\n\005Light\022\020\n\010light_id"
    "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\022\n\nbrightness\030\003 \001(\005"
    "\022\022\n\ncolor_temp\030\004 \001(\005\022\013\n\003hue\030\005 \001(\005\022\022\n\nsat"
    "uration\030\006 \001(\005\022\026\n\016can_color_temp\030\007 \001(\010\022\021\n"
    "\tcan_color\030\010 \001(\010\022\?\n\022current_light_mode\030\t"
    " \001(\0162#.NSPanelEntityState.Light.LightMod"
    "e\"$\n\tLightMode\022\016\n\nCOLOR_TEMP\020\000\022\007\n\003RGB\020\001B"
    "\010\n\006entityb\006proto3"
};
static ::absl::once_flag descriptor_table_protobuf_5fnspanel_5fentity_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protobuf_5fnspanel_5fentity_2eproto = {
    false,
    false,
    377,
    descriptor_table_protodef_protobuf_5fnspanel_5fentity_2eproto,
    "protobuf_nspanel_entity.proto",
    &descriptor_table_protobuf_5fnspanel_5fentity_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_protobuf_5fnspanel_5fentity_2eproto::offsets,
    file_level_enum_descriptors_protobuf_5fnspanel_5fentity_2eproto,
    file_level_service_descriptors_protobuf_5fnspanel_5fentity_2eproto,
};
const ::google::protobuf::EnumDescriptor* NSPanelEntityState_Light_LightMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protobuf_5fnspanel_5fentity_2eproto);
  return file_level_enum_descriptors_protobuf_5fnspanel_5fentity_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t NSPanelEntityState_Light_LightMode_internal_data_[] = {
    131072u, 0u, };
bool NSPanelEntityState_Light_LightMode_IsValid(int value) {
  return 0 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr NSPanelEntityState_Light_LightMode NSPanelEntityState_Light::COLOR_TEMP;
constexpr NSPanelEntityState_Light_LightMode NSPanelEntityState_Light::RGB;
constexpr NSPanelEntityState_Light_LightMode NSPanelEntityState_Light::LightMode_MIN;
constexpr NSPanelEntityState_Light_LightMode NSPanelEntityState_Light::LightMode_MAX;
constexpr int NSPanelEntityState_Light::LightMode_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class NSPanelEntityState_Light::_Internal {
 public:
};

NSPanelEntityState_Light::NSPanelEntityState_Light(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NSPanelEntityState.Light)
}
inline PROTOBUF_NDEBUG_INLINE NSPanelEntityState_Light::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NSPanelEntityState_Light& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

NSPanelEntityState_Light::NSPanelEntityState_Light(
    ::google::protobuf::Arena* arena,
    const NSPanelEntityState_Light& from)
    : ::google::protobuf::Message(arena) {
  NSPanelEntityState_Light* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, light_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, light_id_),
           offsetof(Impl_, current_light_mode_) -
               offsetof(Impl_, light_id_) +
               sizeof(Impl_::current_light_mode_));

  // @@protoc_insertion_point(copy_constructor:NSPanelEntityState.Light)
}
inline PROTOBUF_NDEBUG_INLINE NSPanelEntityState_Light::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void NSPanelEntityState_Light::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, light_id_),
           0,
           offsetof(Impl_, current_light_mode_) -
               offsetof(Impl_, light_id_) +
               sizeof(Impl_::current_light_mode_));
}
NSPanelEntityState_Light::~NSPanelEntityState_Light() {
  // @@protoc_insertion_point(destructor:NSPanelEntityState.Light)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NSPanelEntityState_Light::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NSPanelEntityState_Light::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_._cached_size_),
              false,
          },
          &NSPanelEntityState_Light::MergeImpl,
          &NSPanelEntityState_Light::kDescriptorMethods,
          &descriptor_table_protobuf_5fnspanel_5fentity_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 45, 2> NSPanelEntityState_Light::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NSPanelEntityState_Light_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NSPanelEntityState_Light>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 light_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelEntityState_Light, _impl_.light_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.light_id_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.name_)}},
    // int32 brightness = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelEntityState_Light, _impl_.brightness_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.brightness_)}},
    // int32 color_temp = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelEntityState_Light, _impl_.color_temp_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.color_temp_)}},
    // int32 hue = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelEntityState_Light, _impl_.hue_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.hue_)}},
    // int32 saturation = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelEntityState_Light, _impl_.saturation_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.saturation_)}},
    // bool can_color_temp = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NSPanelEntityState_Light, _impl_.can_color_temp_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.can_color_temp_)}},
    // bool can_color = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(NSPanelEntityState_Light, _impl_.can_color_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.can_color_)}},
    // .NSPanelEntityState.Light.LightMode current_light_mode = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NSPanelEntityState_Light, _impl_.current_light_mode_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.current_light_mode_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 light_id = 1;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.light_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 brightness = 3;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.brightness_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 color_temp = 4;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.color_temp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 hue = 5;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.hue_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 saturation = 6;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.saturation_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool can_color_temp = 7;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.can_color_temp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool can_color = 8;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.can_color_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // .NSPanelEntityState.Light.LightMode current_light_mode = 9;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.current_light_mode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\30\0\4\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "NSPanelEntityState.Light"
    "name"
  }},
};

PROTOBUF_NOINLINE void NSPanelEntityState_Light::Clear() {
// @@protoc_insertion_point(message_clear_start:NSPanelEntityState.Light)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.light_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.current_light_mode_) -
      reinterpret_cast<char*>(&_impl_.light_id_)) + sizeof(_impl_.current_light_mode_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* NSPanelEntityState_Light::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NSPanelEntityState.Light)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 light_id = 1;
  if (this->_internal_light_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_light_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NSPanelEntityState.Light.name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int32 brightness = 3;
  if (this->_internal_brightness() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_brightness(), target);
  }

  // int32 color_temp = 4;
  if (this->_internal_color_temp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_color_temp(), target);
  }

  // int32 hue = 5;
  if (this->_internal_hue() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_hue(), target);
  }

  // int32 saturation = 6;
  if (this->_internal_saturation() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<6>(
            stream, this->_internal_saturation(), target);
  }

  // bool can_color_temp = 7;
  if (this->_internal_can_color_temp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        7, this->_internal_can_color_temp(), target);
  }

  // bool can_color = 8;
  if (this->_internal_can_color() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        8, this->_internal_can_color(), target);
  }

  // .NSPanelEntityState.Light.LightMode current_light_mode = 9;
  if (this->_internal_current_light_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        9, this->_internal_current_light_mode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NSPanelEntityState.Light)
  return target;
}

::size_t NSPanelEntityState_Light::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NSPanelEntityState.Light)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // int32 light_id = 1;
  if (this->_internal_light_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_light_id());
  }

  // int32 brightness = 3;
  if (this->_internal_brightness() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_brightness());
  }

  // int32 color_temp = 4;
  if (this->_internal_color_temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_color_temp());
  }

  // int32 hue = 5;
  if (this->_internal_hue() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_hue());
  }

  // int32 saturation = 6;
  if (this->_internal_saturation() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_saturation());
  }

  // bool can_color_temp = 7;
  if (this->_internal_can_color_temp() != 0) {
    total_size += 2;
  }

  // bool can_color = 8;
  if (this->_internal_can_color() != 0) {
    total_size += 2;
  }

  // .NSPanelEntityState.Light.LightMode current_light_mode = 9;
  if (this->_internal_current_light_mode() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_current_light_mode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NSPanelEntityState_Light::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NSPanelEntityState_Light*>(&to_msg);
  auto& from = static_cast<const NSPanelEntityState_Light&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NSPanelEntityState.Light)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_light_id() != 0) {
    _this->_impl_.light_id_ = from._impl_.light_id_;
  }
  if (from._internal_brightness() != 0) {
    _this->_impl_.brightness_ = from._impl_.brightness_;
  }
  if (from._internal_color_temp() != 0) {
    _this->_impl_.color_temp_ = from._impl_.color_temp_;
  }
  if (from._internal_hue() != 0) {
    _this->_impl_.hue_ = from._impl_.hue_;
  }
  if (from._internal_saturation() != 0) {
    _this->_impl_.saturation_ = from._impl_.saturation_;
  }
  if (from._internal_can_color_temp() != 0) {
    _this->_impl_.can_color_temp_ = from._impl_.can_color_temp_;
  }
  if (from._internal_can_color() != 0) {
    _this->_impl_.can_color_ = from._impl_.can_color_;
  }
  if (from._internal_current_light_mode() != 0) {
    _this->_impl_.current_light_mode_ = from._impl_.current_light_mode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NSPanelEntityState_Light::CopyFrom(const NSPanelEntityState_Light& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NSPanelEntityState.Light)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NSPanelEntityState_Light::InternalSwap(NSPanelEntityState_Light* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.current_light_mode_)
      + sizeof(NSPanelEntityState_Light::_impl_.current_light_mode_)
      - PROTOBUF_FIELD_OFFSET(NSPanelEntityState_Light, _impl_.light_id_)>(
          reinterpret_cast<char*>(&_impl_.light_id_),
          reinterpret_cast<char*>(&other->_impl_.light_id_));
}

::google::protobuf::Metadata NSPanelEntityState_Light::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NSPanelEntityState::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::NSPanelEntityState, _impl_._oneof_case_);
};

void NSPanelEntityState::set_allocated_light(::NSPanelEntityState_Light* light) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_entity();
  if (light) {
    ::google::protobuf::Arena* submessage_arena = light->GetArena();
    if (message_arena != submessage_arena) {
      light = ::google::protobuf::internal::GetOwnedMessage(message_arena, light, submessage_arena);
    }
    set_has_light();
    _impl_.entity_.light_ = light;
  }
  // @@protoc_insertion_point(field_set_allocated:NSPanelEntityState.light)
}
NSPanelEntityState::NSPanelEntityState(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NSPanelEntityState)
}
inline PROTOBUF_NDEBUG_INLINE NSPanelEntityState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NSPanelEntityState& from_msg)
      : entity_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

NSPanelEntityState::NSPanelEntityState(
    ::google::protobuf::Arena* arena,
    const NSPanelEntityState& from)
    : ::google::protobuf::Message(arena) {
  NSPanelEntityState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (entity_case()) {
    case ENTITY_NOT_SET:
      break;
      case kLight:
        _impl_.entity_.light_ = ::google::protobuf::Message::CopyConstruct<::NSPanelEntityState_Light>(arena, *from._impl_.entity_.light_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:NSPanelEntityState)
}
inline PROTOBUF_NDEBUG_INLINE NSPanelEntityState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : entity_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void NSPanelEntityState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NSPanelEntityState::~NSPanelEntityState() {
  // @@protoc_insertion_point(destructor:NSPanelEntityState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NSPanelEntityState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_entity()) {
    clear_entity();
  }
  _impl_.~Impl_();
}

void NSPanelEntityState::clear_entity() {
// @@protoc_insertion_point(one_of_clear_start:NSPanelEntityState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (entity_case()) {
    case kLight: {
      if (GetArena() == nullptr) {
        delete _impl_.entity_.light_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.entity_.light_);
      }
      break;
    }
    case ENTITY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ENTITY_NOT_SET;
}


const ::google::protobuf::MessageLite::ClassData*
NSPanelEntityState::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(NSPanelEntityState, _impl_._cached_size_),
              false,
          },
          &NSPanelEntityState::MergeImpl,
          &NSPanelEntityState::kDescriptorMethods,
          &descriptor_table_protobuf_5fnspanel_5fentity_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> NSPanelEntityState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_NSPanelEntityState_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NSPanelEntityState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .NSPanelEntityState.Light light = 1;
    {PROTOBUF_FIELD_OFFSET(NSPanelEntityState, _impl_.entity_.light_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::NSPanelEntityState_Light>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void NSPanelEntityState::Clear() {
// @@protoc_insertion_point(message_clear_start:NSPanelEntityState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_entity();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* NSPanelEntityState::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NSPanelEntityState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .NSPanelEntityState.Light light = 1;
  if (entity_case() == kLight) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *_impl_.entity_.light_, _impl_.entity_.light_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NSPanelEntityState)
  return target;
}

::size_t NSPanelEntityState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NSPanelEntityState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (entity_case()) {
    // .NSPanelEntityState.Light light = 1;
    case kLight: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.entity_.light_);
      break;
    }
    case ENTITY_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NSPanelEntityState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NSPanelEntityState*>(&to_msg);
  auto& from = static_cast<const NSPanelEntityState&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:NSPanelEntityState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_entity();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kLight: {
        if (oneof_needs_init) {
          _this->_impl_.entity_.light_ =
              ::google::protobuf::Message::CopyConstruct<::NSPanelEntityState_Light>(arena, *from._impl_.entity_.light_);
        } else {
          _this->_impl_.entity_.light_->MergeFrom(from._internal_light());
        }
        break;
      }
      case ENTITY_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NSPanelEntityState::CopyFrom(const NSPanelEntityState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NSPanelEntityState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NSPanelEntityState::InternalSwap(NSPanelEntityState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.entity_, other->_impl_.entity_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata NSPanelEntityState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_protobuf_5fnspanel_5fentity_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
