/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./nspanelmanager/web/components/**/*.{html,js}", "./nspanelmanager/web/static/**/*.{html,js}", "./nspanelmanager/web/templates/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  darkMode: 'selector',
  plugins: [
    require('@tailwindcss/forms'),
    require('daisyui'),
    require('tailwindcss-pseudo-selectors'),
  ],
  daisyui: {
   themes: [
         "light",
         "dark",
         "cupcake",
         "bumblebee",
         "emerald",
         "corporate",
         "synthwave",
         "retro",
         "cyberpunk",
         "valentine",
         "halloween",
         "garden",
         "forest",
         "aqua",
         "lofi",
         "pastel",
         "fantasy",
         "wireframe",
         "black",
         "luxury",
         "dracula",
         "cmyk",
         "autumn",
         "business",
         "acid",
         "lemonade",
         "night",
         "coffee",
         "winter",
         "dim",
         "nord",
         "sunset",
       ],
  }
}
