#define HOME_PAGE_ID 2
#define SWITCH_ROOM_BUTTON_ID 20
#define SWITCH_MODE_BUTTON_ID 8
#define LIGHT_LEVEL_CHANGE_BUTTON_ID 2
#define CEILING_LIGHTS_MASTER_BUTTON_ID 3

#define HOME_PAGE_NAME "home"
