#define HOME_PAGE_ID 2
#define SWITCH_ROOM_BUTTON_ID 20
#define SWITCH_MODE_BUTTON_ID 8
#define CEILING_LIGHTS_RAISE_BUTTON_ID 3
#define CEILING_LIGHTS_LOWER_BUTTON_ID 5

#define HOME_PAGE_NAME "home"