#include <cstdint>
#include <string>

class WeatherIcons {
public:
  struct WeatherIcon {
    const uint8_t weather_code;
    const std::string_view icon_day;
    const std::string_view icon_night;
    const std::string_view text;
  };

  static constexpr const WeatherIcon weather_icons[] = {
      {.weather_code = 0,
       .icon_day = "A",
       .icon_night = "B",
       .text = "Clear sky"},
      {.weather_code = 1,
       .icon_day = "C",
       .icon_night = "D",
       .text = "Mainly clear"},
      {.weather_code = 2,
       .icon_day = "C",
       .icon_night = "D",
       .text = "Partly cloudy"},
      {.weather_code = 3,
       .icon_day = "C",
       .icon_night = "C",
       .text = "Overcast"},
      {.weather_code = 45,
       .icon_day = "G",
       .icon_night = "G",
       .text = "Fog"},
      {.weather_code = 48,
       .icon_day = "G",
       .icon_night = "G",
       .text = "Depositing rime fog"},
      {.weather_code = 51,
       .icon_day = "J",
       .icon_night = "J",
       .text = "Drizzle: Light"},
      {.weather_code = 53,
       .icon_day = "J",
       .icon_night = "J",
       .text = "Drizzle: Moderate"},
      {.weather_code = 55,
       .icon_day = "J",
       .icon_night = "J",
       .text = "Drizzle: Dense"},
      {.weather_code = 56,
       .icon_day = "J",
       .icon_night = "J",
       .text = "Freezing Drizzle: Light"},
      {.weather_code = 57,
       .icon_day = "J",
       .icon_night = "J",
       .text = "Freezing Drizzle: Dense"},
      {.weather_code = 61,
       .icon_day = "J",
       .icon_night = "J",
       .text = "Rain: Slight"},
      {.weather_code = 63,
       .icon_day = "I",
       .icon_night = "I",
       .text = "Rain: Moderate"},
      {.weather_code = 65,
       .icon_day = "I",
       .icon_night = "I",
       .text = "Rain: Heavy"},
      {.weather_code = 66,
       .icon_day = "N",
       .icon_night = "N",
       .text = "Freezing Rain: Light"},
      {.weather_code = 67,
       .icon_day = "N",
       .icon_night = "N",
       .text = "Freezing Rain: Heavy"},
      {.weather_code = 71,
       .icon_day = "L",
       .icon_night = "L",
       .text = "Snow fall: Slight"},
      {.weather_code = 73,
       .icon_day = "M",
       .icon_night = "M",
       .text = "Snow fall: Moderate"},
      {.weather_code = 75,
       .icon_day = "M",
       .icon_night = "M",
       .text = "Snow fall: Heavy"},
      {.weather_code = 77,
       .icon_day = "H",
       .icon_night = "H",
       .text = "Snow grains"},
      {.weather_code = 80,
       .icon_day = "J",
       .icon_night = "J",
       .text = "Rain showers: Slight"},
      {.weather_code = 81,
       .icon_day = "I",
       .icon_night = "I",
       .text = "Rain showers: Moderate"},
      {.weather_code = 82,
       .icon_day = "I",
       .icon_night = "I",
       .text = "Rain showers: Violent"},
      {.weather_code = 85,
       .icon_day = "L",
       .icon_night = "L",
       .text = "Snow showers: Slight"},
      {.weather_code = 86,
       .icon_day = "M",
       .icon_night = "M",
       .text = "Snow showers: Heavy"},
      {.weather_code = 95,
       .icon_day = "Q",
       .icon_night = "Q",
       .text = "Thunderstorm: Slight or moderate"},
      {.weather_code = 96,
       .icon_day = "R",
       .icon_night = "R",
       .text = "Thunderstorm: Slight Hail"},
      {.weather_code = 99,
       .icon_day = "R",
       .icon_night = "R",
       .text = "Thunderstorm: Heavy Hail"}};
};
