/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf_nspanel.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protobuf_nspanel.pb-c.h"
void   nspanel_warning__init
                     (NSPanelWarning         *message)
{
  static const NSPanelWarning init_value = NSPANEL_WARNING__INIT;
  *message = init_value;
}
size_t nspanel_warning__get_packed_size
                     (const NSPanelWarning *message)
{
  assert(message->base.descriptor == &nspanel_warning__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nspanel_warning__pack
                     (const NSPanelWarning *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nspanel_warning__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nspanel_warning__pack_to_buffer
                     (const NSPanelWarning *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nspanel_warning__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NSPanelWarning *
       nspanel_warning__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NSPanelWarning *)
     protobuf_c_message_unpack (&nspanel_warning__descriptor,
                                allocator, len, data);
}
void   nspanel_warning__free_unpacked
                     (NSPanelWarning *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nspanel_warning__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nspanel_status_report__init
                     (NSPanelStatusReport         *message)
{
  static const NSPanelStatusReport init_value = NSPANEL_STATUS_REPORT__INIT;
  *message = init_value;
}
size_t nspanel_status_report__get_packed_size
                     (const NSPanelStatusReport *message)
{
  assert(message->base.descriptor == &nspanel_status_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nspanel_status_report__pack
                     (const NSPanelStatusReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nspanel_status_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nspanel_status_report__pack_to_buffer
                     (const NSPanelStatusReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nspanel_status_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NSPanelStatusReport *
       nspanel_status_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NSPanelStatusReport *)
     protobuf_c_message_unpack (&nspanel_status_report__descriptor,
                                allocator, len, data);
}
void   nspanel_status_report__free_unpacked
                     (NSPanelStatusReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nspanel_status_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nspanel_light_status__init
                     (NSPanelLightStatus         *message)
{
  static const NSPanelLightStatus init_value = NSPANEL_LIGHT_STATUS__INIT;
  *message = init_value;
}
size_t nspanel_light_status__get_packed_size
                     (const NSPanelLightStatus *message)
{
  assert(message->base.descriptor == &nspanel_light_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nspanel_light_status__pack
                     (const NSPanelLightStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nspanel_light_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nspanel_light_status__pack_to_buffer
                     (const NSPanelLightStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nspanel_light_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NSPanelLightStatus *
       nspanel_light_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NSPanelLightStatus *)
     protobuf_c_message_unpack (&nspanel_light_status__descriptor,
                                allocator, len, data);
}
void   nspanel_light_status__free_unpacked
                     (NSPanelLightStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nspanel_light_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nspanel_room_status__init
                     (NSPanelRoomStatus         *message)
{
  static const NSPanelRoomStatus init_value = NSPANEL_ROOM_STATUS__INIT;
  *message = init_value;
}
size_t nspanel_room_status__get_packed_size
                     (const NSPanelRoomStatus *message)
{
  assert(message->base.descriptor == &nspanel_room_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nspanel_room_status__pack
                     (const NSPanelRoomStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nspanel_room_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nspanel_room_status__pack_to_buffer
                     (const NSPanelRoomStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nspanel_room_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NSPanelRoomStatus *
       nspanel_room_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NSPanelRoomStatus *)
     protobuf_c_message_unpack (&nspanel_room_status__descriptor,
                                allocator, len, data);
}
void   nspanel_room_status__free_unpacked
                     (NSPanelRoomStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nspanel_room_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nspanel_weather_update__forecast_item__init
                     (NSPanelWeatherUpdate__ForecastItem         *message)
{
  static const NSPanelWeatherUpdate__ForecastItem init_value = NSPANEL_WEATHER_UPDATE__FORECAST_ITEM__INIT;
  *message = init_value;
}
void   nspanel_weather_update__init
                     (NSPanelWeatherUpdate         *message)
{
  static const NSPanelWeatherUpdate init_value = NSPANEL_WEATHER_UPDATE__INIT;
  *message = init_value;
}
size_t nspanel_weather_update__get_packed_size
                     (const NSPanelWeatherUpdate *message)
{
  assert(message->base.descriptor == &nspanel_weather_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nspanel_weather_update__pack
                     (const NSPanelWeatherUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nspanel_weather_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nspanel_weather_update__pack_to_buffer
                     (const NSPanelWeatherUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nspanel_weather_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NSPanelWeatherUpdate *
       nspanel_weather_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NSPanelWeatherUpdate *)
     protobuf_c_message_unpack (&nspanel_weather_update__descriptor,
                                allocator, len, data);
}
void   nspanel_weather_update__free_unpacked
                     (NSPanelWeatherUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nspanel_weather_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nspanel_warning__field_descriptors[2] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NSPanelWarning, level),
    &nspanel_warning_level__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWarning, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_warning__field_indices_by_name[] = {
  0,   /* field[0] = level */
  1,   /* field[1] = text */
};
static const ProtobufCIntRange nspanel_warning__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nspanel_warning__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelWarning",
  "NSPanelWarning",
  "NSPanelWarning",
  "",
  sizeof(NSPanelWarning),
  2,
  nspanel_warning__field_descriptors,
  nspanel_warning__field_indices_by_name,
  1,  nspanel_warning__number_ranges,
  (ProtobufCMessageInit) nspanel_warning__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nspanel_status_report__state__enum_values_by_number[5] =
{
  { "ONLINE", "NSPANEL_STATUS_REPORT__STATE__ONLINE", 0 },
  { "OFFLINE", "NSPANEL_STATUS_REPORT__STATE__OFFLINE", 1 },
  { "UPDATING_TFT", "NSPANEL_STATUS_REPORT__STATE__UPDATING_TFT", 2 },
  { "UPDATING_FIRMWARE", "NSPANEL_STATUS_REPORT__STATE__UPDATING_FIRMWARE", 3 },
  { "UPDATING_LITTLEFS", "NSPANEL_STATUS_REPORT__STATE__UPDATING_LITTLEFS", 4 },
};
static const ProtobufCIntRange nspanel_status_report__state__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex nspanel_status_report__state__enum_values_by_name[5] =
{
  { "OFFLINE", 1 },
  { "ONLINE", 0 },
  { "UPDATING_FIRMWARE", 3 },
  { "UPDATING_LITTLEFS", 4 },
  { "UPDATING_TFT", 2 },
};
const ProtobufCEnumDescriptor nspanel_status_report__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NSPanelStatusReport.state",
  "state",
  "NSPanelStatusReport__State",
  "",
  5,
  nspanel_status_report__state__enum_values_by_number,
  5,
  nspanel_status_report__state__enum_values_by_name,
  1,
  nspanel_status_report__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nspanel_status_report__field_descriptors[8] =
{
  {
    "nspanel_state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NSPanelStatusReport, nspanel_state),
    &nspanel_status_report__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_progress",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelStatusReport, update_progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelStatusReport, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heap_used_pct",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelStatusReport, heap_used_pct),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_address",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelStatusReport, mac_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelStatusReport, temperature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_address",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelStatusReport, ip_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warnings",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NSPanelStatusReport, n_warnings),
    offsetof(NSPanelStatusReport, warnings),
    &nspanel_warning__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_status_report__field_indices_by_name[] = {
  3,   /* field[3] = heap_used_pct */
  6,   /* field[6] = ip_address */
  4,   /* field[4] = mac_address */
  0,   /* field[0] = nspanel_state */
  2,   /* field[2] = rssi */
  5,   /* field[5] = temperature */
  1,   /* field[1] = update_progress */
  7,   /* field[7] = warnings */
};
static const ProtobufCIntRange nspanel_status_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor nspanel_status_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelStatusReport",
  "NSPanelStatusReport",
  "NSPanelStatusReport",
  "",
  sizeof(NSPanelStatusReport),
  8,
  nspanel_status_report__field_descriptors,
  nspanel_status_report__field_indices_by_name,
  1,  nspanel_status_report__number_ranges,
  (ProtobufCMessageInit) nspanel_status_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nspanel_light_status__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelLightStatus, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelLightStatus, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_dim",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NSPanelLightStatus, can_dim),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_color_temperature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NSPanelLightStatus, can_color_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_rgb",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NSPanelLightStatus, can_rgb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_light_status__field_indices_by_name[] = {
  3,   /* field[3] = can_color_temperature */
  2,   /* field[2] = can_dim */
  4,   /* field[4] = can_rgb */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange nspanel_light_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nspanel_light_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelLightStatus",
  "NSPanelLightStatus",
  "NSPanelLightStatus",
  "",
  sizeof(NSPanelLightStatus),
  5,
  nspanel_light_status__field_descriptors,
  nspanel_light_status__field_indices_by_name,
  1,  nspanel_light_status__number_ranges,
  (ProtobufCMessageInit) nspanel_light_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nspanel_room_status__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelRoomStatus, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelRoomStatus, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "average_dim_level",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelRoomStatus, average_dim_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ceiling_lights_dim_level",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelRoomStatus, ceiling_lights_dim_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "table_lights_dim_level",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelRoomStatus, table_lights_dim_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lights",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NSPanelRoomStatus, n_lights),
    offsetof(NSPanelRoomStatus, lights),
    &nspanel_light_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_room_status__field_indices_by_name[] = {
  2,   /* field[2] = average_dim_level */
  3,   /* field[3] = ceiling_lights_dim_level */
  0,   /* field[0] = id */
  5,   /* field[5] = lights */
  1,   /* field[1] = name */
  4,   /* field[4] = table_lights_dim_level */
};
static const ProtobufCIntRange nspanel_room_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor nspanel_room_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelRoomStatus",
  "NSPanelRoomStatus",
  "NSPanelRoomStatus",
  "",
  sizeof(NSPanelRoomStatus),
  6,
  nspanel_room_status__field_descriptors,
  nspanel_room_status__field_indices_by_name,
  1,  nspanel_room_status__number_ranges,
  (ProtobufCMessageInit) nspanel_room_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nspanel_weather_update__forecast_item__field_descriptors[5] =
{
  {
    "weather_icon",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate__ForecastItem, weather_icon),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "precipitation_string",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate__ForecastItem, precipitation_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature_maxmin_string",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate__ForecastItem, temperature_maxmin_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wind_string",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate__ForecastItem, wind_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display_string",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate__ForecastItem, display_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_weather_update__forecast_item__field_indices_by_name[] = {
  4,   /* field[4] = display_string */
  1,   /* field[1] = precipitation_string */
  2,   /* field[2] = temperature_maxmin_string */
  0,   /* field[0] = weather_icon */
  3,   /* field[3] = wind_string */
};
static const ProtobufCIntRange nspanel_weather_update__forecast_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nspanel_weather_update__forecast_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelWeatherUpdate.ForecastItem",
  "ForecastItem",
  "NSPanelWeatherUpdate__ForecastItem",
  "",
  sizeof(NSPanelWeatherUpdate__ForecastItem),
  5,
  nspanel_weather_update__forecast_item__field_descriptors,
  nspanel_weather_update__forecast_item__field_indices_by_name,
  1,  nspanel_weather_update__forecast_item__number_ranges,
  (ProtobufCMessageInit) nspanel_weather_update__forecast_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nspanel_weather_update__field_descriptors[9] =
{
  {
    "forecast_items",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NSPanelWeatherUpdate, n_forecast_items),
    offsetof(NSPanelWeatherUpdate, forecast_items),
    &nspanel_weather_update__forecast_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_weather_icon",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate, current_weather_icon),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_temperature_string",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate, current_temperature_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_maxmin_temperature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate, current_maxmin_temperature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_wind_string",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate, current_wind_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sunrise_string",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate, sunrise_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sunset_string",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate, sunset_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_precipitation_string",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NSPanelWeatherUpdate, current_precipitation_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_field",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(NSPanelWeatherUpdate, n_test_field),
    offsetof(NSPanelWeatherUpdate, test_field),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_weather_update__field_indices_by_name[] = {
  3,   /* field[3] = current_maxmin_temperature */
  7,   /* field[7] = current_precipitation_string */
  2,   /* field[2] = current_temperature_string */
  1,   /* field[1] = current_weather_icon */
  4,   /* field[4] = current_wind_string */
  0,   /* field[0] = forecast_items */
  5,   /* field[5] = sunrise_string */
  6,   /* field[6] = sunset_string */
  8,   /* field[8] = test_field */
};
static const ProtobufCIntRange nspanel_weather_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor nspanel_weather_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelWeatherUpdate",
  "NSPanelWeatherUpdate",
  "NSPanelWeatherUpdate",
  "",
  sizeof(NSPanelWeatherUpdate),
  9,
  nspanel_weather_update__field_descriptors,
  nspanel_weather_update__field_indices_by_name,
  1,  nspanel_weather_update__number_ranges,
  (ProtobufCMessageInit) nspanel_weather_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nspanel_warning_level__enum_values_by_number[6] =
{
  { "CRITICAL", "NSPANEL_WARNING_LEVEL__CRITICAL", 0 },
  { "ERROR", "NSPANEL_WARNING_LEVEL__ERROR", 1 },
  { "WARNING", "NSPANEL_WARNING_LEVEL__WARNING", 2 },
  { "INFO", "NSPANEL_WARNING_LEVEL__INFO", 3 },
  { "DEBUG", "NSPANEL_WARNING_LEVEL__DEBUG", 4 },
  { "TRACE", "NSPANEL_WARNING_LEVEL__TRACE", 5 },
};
static const ProtobufCIntRange nspanel_warning_level__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex nspanel_warning_level__enum_values_by_name[6] =
{
  { "CRITICAL", 0 },
  { "DEBUG", 4 },
  { "ERROR", 1 },
  { "INFO", 3 },
  { "TRACE", 5 },
  { "WARNING", 2 },
};
const ProtobufCEnumDescriptor nspanel_warning_level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NSPanelWarningLevel",
  "NSPanelWarningLevel",
  "NSPanelWarningLevel",
  "",
  6,
  nspanel_warning_level__enum_values_by_number,
  6,
  nspanel_warning_level__enum_values_by_name,
  1,
  nspanel_warning_level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
