#ifndef PROTOBUF_DEFINES
#define PROTOBUF_DEFINES

#include <protobuf_nspanel.h>

// Global protobuf defines
#define PROTOBUF_DESERIALIZE_MAX_SIZE 4096

// NSPanel config defines
#define PROTOBUF_NSPANEL_CONFIG NSPanelConfig<64, 64, 255, 255, 255, 255, 16, 32>

// Room defines
#define PROTOBUF_ROOM_NAME_LENGTH 32
#define PROTOBUF_ROOM_MAX_NUM_LIGHTS 64
#define PROTOBUF_ROOM_MAX_NUM_SCENES 16

// Light defines
#define PROTOBUF_LIGHT_NAME_LENGTH 32

// Scene defines
#define PROTOBUF_SCENE_NAME_LENGTH 32

// MQTTManager command defines
#define PROTOBUF_MQTTMANAGER_CMD_MAX_NUM_LIGHTS 256
#define PROTOBUF_MQTTMANAGER_CMD_MAX_SIZE 512
#define PROTOBUF_NSPANEL_WARNING_MAX_TEXT_LENGTH 256

// NSPanel status report defines
#define PROTOBUF_NSPANEL_STATUS_REPORT_MAX_WARNINGS 16
#define PROTOBUF_NSPANEL_STATUS_MAX_SIZE 512

// Define weather
#define PROTOBUF_NSPANEL_WEATHER_UPDATE_MAX_SIZE 1024
#define PROTOBUF_NSPANEL_WEATHER_UPDATE NSPanelWeatherUpdate<8, 8, 8, 16, 16, 16, 8, 8, 8, 8, 8, 8, 8>

// Protobuf object defines with template arguments
#define PROTOBUF_NSPANEL_ROOM_STATUS NSPanelRoomStatus<PROTOBUF_ROOM_NAME_LENGTH, PROTOBUF_ROOM_MAX_NUM_LIGHTS, PROTOBUF_LIGHT_NAME_LENGTH, PROTOBUF_ROOM_MAX_NUM_SCENES, PROTOBUF_SCENE_NAME_LENGTH>
#define PROTOBUF_MQTTMANAGER_CMD_LIGHT_COMMAND NSPanelMQTTManagerCommand<PROTOBUF_MQTTMANAGER_CMD_MAX_NUM_LIGHTS>::LightCommand<PROTOBUF_MQTTMANAGER_CMD_MAX_NUM_LIGHTS>
#define PROTOBUF_MQTTMANAGER_CMD NSPanelMQTTManagerCommand<PROTOBUF_MQTTMANAGER_CMD_MAX_NUM_LIGHTS>
#define PROTOBUF_NSPANEL_LIGHT_STATUS NSPanelLightStatus<PROTOBUF_LIGHT_NAME_LENGTH>
#define PROTOBUF_NSPANEL_SCENE NSPanelScene<PROTOBUF_SCENE_NAME_LENGTH>
#define PROTOBUF_NSPANEL_WARNING NSPanelWarning<PROTOBUF_NSPANEL_WARNING_MAX_TEXT_LENGTH>
#define PROTOBUF_NSPANEL_STATUS_REPORT NSPanelStatusReport<32, 16, 16, PROTOBUF_NSPANEL_STATUS_REPORT_MAX_WARNINGS, PROTOBUF_NSPANEL_WARNING_MAX_TEXT_LENGTH>

#endif