/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "protobuf_nspanel.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(NSPanelStatusReport, NSPanelStatusReport, AUTO)


PB_BIND(NSPanelStatusReport_NSPanelWarning, NSPanelStatusReport_NSPanelWarning, AUTO)


PB_BIND(NSPanelLightStatus, NSPanelLightStatus, AUTO)


PB_BIND(NSPanelRoomStatus, NSPanelRoomStatus, AUTO)





