# Generated by Django 4.1.7 on 2023-02-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_firmware_binary_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firmware',
        ),
    ]
