# Generated by Django 4.1.7 on 2023-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_light_color_temperature_topic_light_rgb_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='friendly_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
