# Generated by Django 4.1.7 on 2023-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_light_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='color_temperature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='light',
            name='rgb_state_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='light',
            name='cmd_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='light',
            name='color_temperature_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='light',
            name='rgb_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='light',
            name='state_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
