# Generated by Django 4.1.7 on 2023-02-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_light_color_temperature_light_rgb_state_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='is_ceiling_light',
            field=models.BooleanField(default=False),
        ),
    ]
