# Generated by Django 4.1.7 on 2023-03-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_light_is_ceiling_light'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
