# Generated by Django 4.1.7 on 2023-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='type',
            field=models.CharField(default='manual', max_length=16),
        ),
    ]
