# Generated by Django 4.1.7 on 2023-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_light_openhab_control_mode_light_openhab_item_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='status_data',
            field=models.JSONField(default={'free_heap': 0, 'mac': '??:??:??:??:??:??', 'rssi': 0}),
        ),
    ]
