# Generated by Django 4.1.7 on 2023-04-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_remove_light_room_view_page_light_room_view_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nspanel',
            name='status_data',
        ),
        migrations.AddField(
            model_name='nspanel',
            name='heap_used_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='wifi_rssi',
            field=models.IntegerField(default=0),
        ),
    ]
