# Generated by Django 4.1.7 on 2023-04-12 21:22

from django.db import migrations


def add_first_room_if_no_exists(apps, schema_editor):
    Room = apps.get_model("web", "Room")
    if len(Room.objects.all()) == 0:
        room = Room()
        room.friendly_name = "Dummy room"
        room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_light_openhab_item_rgb'),
    ]

    operations = [
        migrations.RunPython(add_first_room_if_no_exists)
    ]
