# Generated by Django 4.1.7 on 2023-04-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20230412_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='openhab_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
