# Generated by Django 4.1.7 on 2023-05-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_light_openhab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='button1_detached_mode_light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.light'),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='button1_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='button2_detached_mode_light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.light'),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='button2_mode',
            field=models.IntegerField(default=0),
        ),
    ]
