# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf_formats.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'protobuf_formats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf_formats.proto*\"\n\x0btime_format\x12\t\n\x05\x41M_PM\x10\x00\x12\x08\n\x04\x46ULL\x10\x01*1\n\x12temperature_format\x12\x0e\n\nFAHRENHEIT\x10\x00\x12\x0b\n\x07\x43\x45LCIUS\x10\x01*;\n\x11wind_speed_format\x12\x08\n\x04KM_H\x10\x00\x12\x07\n\x03M_S\x10\x01\x12\x08\n\x04MP_H\x10\x02\x12\t\n\x05KNOTS\x10\x03*2\n\x14precipitation_format\x12\x0f\n\x0bMILLIMETERS\x10\x00\x12\t\n\x05INCES\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_formats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIME_FORMAT']._serialized_start=26
  _globals['_TIME_FORMAT']._serialized_end=60
  _globals['_TEMPERATURE_FORMAT']._serialized_start=62
  _globals['_TEMPERATURE_FORMAT']._serialized_end=111
  _globals['_WIND_SPEED_FORMAT']._serialized_start=113
  _globals['_WIND_SPEED_FORMAT']._serialized_end=172
  _globals['_PRECIPITATION_FORMAT']._serialized_start=174
  _globals['_PRECIPITATION_FORMAT']._serialized_end=224
# @@protoc_insertion_point(module_scope)
