# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2023-02-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_dim', models.BooleanField(default=False)),
                ('can_rgb', models.BooleanField(default=False)),
                ('can_color_temperature', models.BooleanField(default=False)),
                ('cmd_topic', models.CharField(max_length=255)),
                ('state_topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NSPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('friendly_name', models.CharField(max_length=100)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='nspanel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Room'),
        ),
        migrations.AddField(
            model_name='light',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Room'),
        ),
    ]
