syntax = "proto3";

// Protobufs defined in this .proto file are used to communicate with the MQTTManager
// and control/update individual entities.

message NSPanelEntityState {
  message Light {
    enum LightMode {
      COLOR_TEMP = 0;
      RGB = 1;
    }

    int32 light_id = 1;
    string name = 2;
    int32 brightness = 3;
    int32 color_temp = 4;
    int32 hue = 5;
    int32 saturation = 6;

    bool can_color_temp = 7;
    bool can_color = 8;
    LightMode current_light_mode = 9;
    bool state = 10;
  }

  message Thermostat {
    int32 thermostat_id = 1;
    string name = 2;
    float current_temperature = 3;
    bool has_current_temperature = 4;
    float set_temperature = 5;
    float step_size = 6;

    message ThermostatOption {
      string name = 1;
      string current_value = 2;
      string current_icon = 3;
      message ThermostatOptionValue {
        string value = 1;
        string icon = 2;
      }

      repeated ThermostatOptionValue options = 4;
    }
    repeated ThermostatOption options = 7;
  }

  message MediaPlayer {
    enum PlaybackState {
      UNKNOWN = 0;
      OFF = 1;
      ON = 2;
      IDLE = 3;
      PLAYING = 4;
      PAUSED = 5;
      BUFFERING = 6;
    }

    int32 media_player_id = 1;
    string name = 2;
    PlaybackState state = 3;
    string media_title = 4;
    string media_artist = 5;

    int32 volume = 6; // Volume in 0-100%
    bool is_muted = 7;

    // Some setups (for example multi-room audio matrices) have a separate volume
    // for the source feeding this player. Only valid if has_source_volume is set.
    bool has_source_volume = 8;
    int32 source_volume = 9; // Volume in 0-100%

    bool can_play = 10;
    bool can_pause = 11;
    bool can_next_track = 12;
    bool can_previous_track = 13;
    bool can_set_volume = 14;
    bool can_mute = 15;
  }

  oneof entity {
    Light light = 1;
    Thermostat thermostat = 2;
    MediaPlayer media_player = 3;
  }
}
