# Generated by Django 4.1.7 on 2023-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='ip_address',
            field=models.CharField(default='', max_length=15),
        ),
    ]
