# Generated by Django 4.1.7 on 2023-02-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_nspanel_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='version',
            field=models.CharField(default='', max_length=15),
        ),
    ]
