# Generated by Django 4.1.7 on 2023-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_firmware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='binary_data',
            field=models.FileField(upload_to=''),
        ),
    ]
