# Generated by Django 4.1.7 on 2023-03-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_light_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='cmd_topic',
        ),
        migrations.RemoveField(
            model_name='light',
            name='color_temperature',
        ),
        migrations.RemoveField(
            model_name='light',
            name='color_temperature_topic',
        ),
        migrations.RemoveField(
            model_name='light',
            name='rgb_state_topic',
        ),
        migrations.RemoveField(
            model_name='light',
            name='rgb_topic',
        ),
        migrations.RemoveField(
            model_name='light',
            name='state_topic',
        ),
    ]
