# Generated by Django 4.1.7 on 2023-03-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_light_cmd_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='openhab_item_color_temp',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='light',
            name='openhab_item_dimmer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
