# Generated by Django 4.1.7 on 2023-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_light_openhab_item_color_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='openhab_control_mode',
            field=models.CharField(default='dimmer', max_length=32),
        ),
        migrations.AddField(
            model_name='light',
            name='openhab_item_switch',
            field=models.CharField(default='', max_length=255),
        ),
    ]
