# Generated by Django 4.1.7 on 2023-03-28 20:54

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_nspanel_status_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nspanel',
            name='status_data',
            field=models.JSONField(default=web.models._default_nspanel_status_data),
        ),
    ]
