# Generated by Django 4.1.7 on 2023-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_remove_nspanel_status_data_nspanel_heap_used_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='home_assistant_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
