# Generated by Django 4.1.7 on 2023-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_light_home_assistant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='openhab_item_rgb',
            field=models.CharField(default='', max_length=255),
        ),
    ]
