# Generated by Django 4.1.7 on 2023-05-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_scene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='name',
            new_name='friendly_name',
        ),
    ]
