# Generated by Django 4.1.7 on 2023-05-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_remove_scene_lights_lightstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightstate',
            name='color_temperature',
            field=models.IntegerField(default=4000),
        ),
    ]
