# Generated by Django 4.1.7 on 2023-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_lightstate_color_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
