# Generated by Django 4.1.7 on 2023-07-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_nspanel_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSPanelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('nspanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nspanel')),
            ],
        ),
    ]
