# Generated by Django 4.1.7 on 2023-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_nspanelsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='md5_data_file',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='md5_firmware',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='md5_tft_file',
            field=models.CharField(default='', max_length=64),
        ),
    ]
