# Generated by Django 4.1.7 on 2023-08-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_nspanel_md5_data_file_nspanel_md5_firmware_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nspanel',
            name='last_seen',
        ),
    ]
