# Generated by Django 4.2.6 on 2023-11-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_remove_nspanel_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayGroupBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_num', models.IntegerField(default=1)),
                ('nspanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nspanel')),
            ],
        ),
        migrations.CreateModel(
            name='RelayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(default='', max_length=255)),
                ('relay_group_bindings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.relaygroupbinding')),
            ],
        ),
    ]
