# Generated by Django 4.2.6 on 2024-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_nspanel_register_relay1_as_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scene_type',
            field=models.CharField(default='nspm_scene', max_length=64),
            preserve_default=False,
        ),
    ]
