# Generated by Django 4.2.6 on 2024-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_scene_scene_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='backend_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
