# Generated by Django 4.2.6 on 2024-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_scene_backend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
