# Generated by Django 4.2.6 on 2024-08-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_nspanel_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
