# Generated by Django 4.2.6 on 2024-09-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_nspanel_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nspanel',
            name='heap_used_pct',
        ),
        migrations.RemoveField(
            model_name='nspanel',
            name='online_state',
        ),
        migrations.RemoveField(
            model_name='nspanel',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='nspanel',
            name='wifi_rssi',
        ),
    ]
