# Generated by Django 5.1.1 on 2024-12-26 16:53

import django.db.models.deletion
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_remove_nspanel_heap_used_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEntitiesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=web.models.RoomEntitiesPage.get_disp_order)),
                ('page_type', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.room')),
            ],
        ),
    ]
