# Generated by Django 5.1.1 on 2024-12-26 17:15

import django.db.models.deletion
from django.db import migrations, models

def transfer_lights_to_entities_pages(apps, schema_editor):
    # Find existing lights and how many of them there are.
    room_model = apps.get_model("web", "Room")
    light_model = apps.get_model("web", "Light")
    entity_page_model = apps.get_model("web", "RoomEntitiesPage")

    for room in room_model.objects.all():
        # Find number of light models
        lights = light_model.objects.filter(room=room)
        model = None
        if lights.count() <= 4:
            model = entity_page_model.objects.create(
                room = room,
                display_order = 0,
                page_type = 4
            )
        elif lights.count() <= 8:
            model = entity_page_model.objects.create(
                room = room,
                display_order = 0,
                page_type = 8
            )
        else:
            model = entity_page_model.objects.create(
                room = room,
                display_order = 0,
                page_type = 12
            )
        index = 0
        for light in light_model.objects.filter(room=room).order_by("room_view_position"):
            light.entities_page = model
            light.room_view_position = index
            light.save()
            index += 1

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_roomentitiespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='entities_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.roomentitiespage'),
        ),
        migrations.RunPython(transfer_lights_to_entities_pages),
    ]
