# Generated by Django 5.1.1 on 2024-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_light_entities_page_alter_light_room_view_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomentitiespage',
            name='display_order',
            field=models.IntegerField(),
        ),
    ]
