# Generated by Django 5.1.1 on 2024-12-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_light_entities_page_alter_light_room_view_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='entities_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.roomentitiespage'),
        ),
        migrations.AlterField(
            model_name='light',
            name='room_view_position',
            field=models.IntegerField(),
        ),
    ]
