# Generated by Django 5.1.1 on 2024-12-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_light_entities_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='controlled_by_nspanel_main_page',
            field=models.BooleanField(default=True),
        ),
    ]
