# Generated by Django 5.1.1 on 2024-12-27 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_roomentitiespage_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.room'),
        ),
    ]
