# Generated by Django 5.1.1 on 2024-12-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_light_controlled_by_nspanel_main_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_view_position', models.IntegerField()),
                ('friendly_name', models.CharField(max_length=32)),
                ('type', models.CharField(default='manual', max_length=16)),
                ('home_assistant_name', models.CharField(default='', max_length=128)),
                ('openhab_name', models.CharField(default='', max_length=255)),
                ('openhab_item_switch', models.CharField(default='', max_length=255)),
                ('entities_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.roomentitiespage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.room')),
            ],
        ),
    ]
