# Generated by Django 5.1.1 on 2025-01-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomentitiespage',
            name='is_scenes_page',
            field=models.BooleanField(default=False),
        ),
    ]
