# Generated by Django 5.1.1 on 2025-02-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_roomentitiespage_is_scenes_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nspanel',
            name='ip_address',
        ),
    ]
