# Generated by Django 5.1.1 on 2025-03-02 14:05

import django.db.models.deletion
from django.db import migrations, models


def transfer_scenes_to_entities_pages(apps, schema_editor):
    # Find existing lights and how many of them there are.
    room_model = apps.get_model("web", "Room")
    scene_model = apps.get_model("web", "Scene")
    entity_page_model = apps.get_model("web", "RoomEntitiesPage")

    # Attach scenes that is attached to a room to the RoomEntitiesPage for that room
    for scene in scene_model.objects.all():
        scene_pages = entity_page_model.objects.filter(room=scene.room, is_scenes_page=True)
        scene_page = None
        if scene_pages.count() == 0:
            model = entity_page_model.objects.create(
                room = scene.room,
                display_order = 0,
                page_type = 4,
                is_scenes_page = True
            )
            model.save();
            scene_page = model
            if scene.room:
                print("Created RoomEntitiesPage for room", scene.room.id)
            else:
                print("Created RoomEntitiesPage for global scenes")
        else:
            scene_page = scene_pages.first()

        scene.entities_page = scene_page
        scene.room_view_position = scene_page.scene_set.count()
        scene.save()
        print("Updating scene", scene.id, " to be attached to RoomEntitiesPage", scene_page.id, "in slot", scene.room_view_position)

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_remove_nspanel_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='entities_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.roomentitiespage'),
        ),
        migrations.AddField(
            model_name='scene',
            name='room_view_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomentitiespage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.room'),
        ),
        migrations.RunPython(transfer_scenes_to_entities_pages),
    ]
