# Generated by Django 5.1.1 on 2025-04-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_roomentitiespage_is_global_scenes_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nspanel',
            name='register_relay1_as_light',
        ),
        migrations.RemoveField(
            model_name='nspanel',
            name='register_relay2_as_light',
        ),
    ]
