# Generated by Django 5.1.1 on 2025-05-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_remove_nspanel_register_relay1_as_light_and_more'),
    ]

    operations = [
    ]
