# Generated by Django 5.1.1 on 2025-07-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_merge_20250504_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(default='', max_length=255)),
                ('entity_type', models.CharField(choices=[('light', 'Light'), ('switch', 'Switch')], max_length=64)),
                ('entity_data', models.JSONField(default={})),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.room')),
            ],
        ),
    ]
