# Generated by Django 5.1.1 on 2025-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_data',
            field=models.JSONField(default=dict),
        ),
    ]
