# Generated by Django 5.1.1 on 2025-07-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    def convert_switches_to_entities(apps, schema_editor):
        Entity = apps.get_model('web', 'Entity')
        Switch = apps.get_model('web', 'Switch')

        for switch in Switch.objects.all():
            Entity.objects.create(
                room=switch.room,
                friendly_name=switch.friendly_name,
                entities_page=switch.room.entities_page,
                room_view_position=switch.room.entities_page.room_view_position,
                entity_type='switch',
                entity_data={
                    'controller': switch.type,
                    'home_assistant_name': switch.home_assistant_name,
                    'openhab_name': switch.openhab_name,
                    'openhab_item_switch': switch.openhab_item_switch,
                },
            )
            switch.delete()

    dependencies = [
        ('web', '0056_alter_entity_entity_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entities_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.roomentitiespage'),
        ),
        migrations.AddField(
            model_name='entity',
            name='room_view_position',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(convert_switches_to_entities),
    ]
