# Generated by Django 5.1.1 on 2025-07-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    def convert_switches_to_entities(apps, schema_editor):
        Entity = apps.get_model('web', 'Entity')
        Switch = apps.get_model('web', 'Switch')

        for switch in Switch.objects.all():
            Entity.objects.create(
                room=switch.room,
                friendly_name=switch.friendly_name,
                entities_page=switch.entities_page,
                room_view_position=switch.room_view_position,
                entity_type='switch',
                entity_data={
                    'controller': switch.type,
                    'home_assistant_name': switch.home_assistant_name,
                    'openhab_name': switch.openhab_name,
                    'openhab_item_switch': switch.openhab_item_switch,
                },
            )
            switch.delete()


    def convert_lights_to_entities(apps, schema_editor):
        Entity = apps.get_model('web', 'Entity')
        Light = apps.get_model('web', 'Light')

        for light in Light.objects.all():
            Entity.objects.create(
                id=light.id,
                room=light.room,
                friendly_name=light.friendly_name,
                entities_page=light.entities_page,
                room_view_position=light.room_view_position,
                entity_type='light',
                entity_data={
                    'controller': light.type,
                    'home_assistant_name': light.home_assistant_name,
                    'openhab_name': light.openhab_name,
                    'openhab_control_mode': light.openhab_control_mode,
                    'openhab_item_switch': light.openhab_item_switch,
                    'openhab_item_dimmer': light.openhab_item_dimmer,
                    'openhab_item_color_temp': light.openhab_item_color_temp,
                    'openhab_item_rgb': light.openhab_item_rgb,
                    'can_dim': light.can_dim,
                    'can_color_temperature': light.can_color_temperature,
                    'can_rgb': light.can_rgb,
                    'is_ceiling_light': light.is_ceiling_light,
                },
            )
            light.delete()

    dependencies = [
        ('web', '0056_alter_entity_entity_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entities_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.roomentitiespage'),
        ),
        migrations.AddField(
            model_name='entity',
            name='room_view_position',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(convert_lights_to_entities),
        migrations.RunPython(convert_switches_to_entities),
    ]
