# Generated by Django 5.1.1 on 2025-07-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_entity_entities_page_entity_room_view_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightstate',
            name='light',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.entity'),
        ),
    ]
