# Generated by Django 5.1.1 on 2025-07-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_alter_lightstate_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nspanel',
            name='button2_detached_mode_light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.entity'),
        ),
        migrations.AlterField(
            model_name='nspanel',
            name='button1_detached_mode_light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='web.entity'),
        ),
        migrations.RemoveField(
            model_name='switch',
            name='entities_page',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='room',
        ),
        migrations.DeleteModel(
            name='Light',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
