# Generated by Django 5.1.1 on 2025-07-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_alter_nspanel_button2_detached_mode_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('light', 'Light'), ('switch', 'Switch'), ('button', 'Button')], max_length=64),
        ),
    ]
