# Generated by Django 5.1.1 on 2025-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_entity_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_temp_provider',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_temp_sensor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
