# Generated by Django 5.1.1 on 2025-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_room_room_temp_provider_room_room_temp_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_temp_provider',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_temp_sensor',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
