# Generated by Django 5.1.1 on 2025-07-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_alter_room_room_temp_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_temp_provider',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_temp_sensor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
