# Generated by Django 5.1.1 on 2025-08-02 11:46

from django.db import migrations


def create_message(apps, schema_editor):
    Message = apps.get_model('web', 'Message')
    new_msg = Message()
    new_msg.title = "[2025-08-02] Home Assistant Add-on Repository will switch URL to beta branch."
    new_msg.message = """
    The Home Assistant Add-on Repository for beta release will switch its URL to the beta branch starting from Dec 1st, 2025.
    The new URL for the beta version of the addon will be as follows: https://github.com/NSPManager/NSPanelManager#beta
    """
    new_msg.save()

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_message'),
    ]

    operations = [
        migrations.RunPython(create_message)
    ]
