# Generated by Django 5.1.1 on 2025-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('light', 'Light'), ('switch', 'Switch'), ('button', 'Button'), ('thermostat', 'Thermostat')], max_length=64),
        ),
    ]
