# Generated by Django 5.1.1 on 2026-01-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_entity_entity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nspanel',
            old_name='button1_detached_mode_light',
            new_name='button1_detached_mode_entity',
        ),
        migrations.RenameField(
            model_name='nspanel',
            old_name='button2_detached_mode_light',
            new_name='button2_detached_mode_entity',
        ),
    ]
