# Generated by Django 5.1.1 on 2026-02-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_rename_button1_detached_mode_light_nspanel_button1_detached_mode_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='model',
            field=models.CharField(choices=[('sonoff', 'Sonoff'), ('custom', 'Custom'), ('web', 'Web')], default='sonoff', max_length=32),
            preserve_default=False,
        ),
    ]
