# Generated by Django 5.1.1 on 2026-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_nspanel_button1_long_detached_mode_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nspanel',
            name='button1_fallback_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='button1_long_fallback_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='button2_fallback_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nspanel',
            name='button2_long_fallback_mode',
            field=models.IntegerField(default=0),
        ),
    ]
