# Generated by Django 5.1.1 on 2026-03-22 10:19

import json

from django.db import migrations


def migrate_thermostat_step_size_to_generic(apps, schema_editor):
    Entities = apps.get_model("web", "Entity")
    for entity in Entities.objects.all():
        json_data = entity.entity_data
        if "openhab_step_size" in json_data:
            json_data["step_size"] = json_data["openhab_step_size"]
            del json_data["openhab_step_size"]
        entity.entity_data = json_data
        entity.save()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0067_nspanel_model"),
    ]

    operations = [migrations.RunPython(migrate_thermostat_step_size_to_generic)]
