# Generated by Django 5.1.1 on 2026-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_auto_20260322_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('light', 'Light'), ('switch', 'Switch'), ('button', 'Button'), ('thermostat', 'Thermostat'), ('media_player', 'Media Player')], max_length=64),
        ),
    ]
