on:
  pull_request:
    paths: ['docs/**']

permissions:
  contents: read

jobs:
  build-doc:
    name: Build documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Move to docs
        run: cd docs
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 21
      - name: Install dependencies
        run: cd docs && yarn install --frozen-lockfile
      - name: Build documentation website
        # Check URLs are valid, path to images, etc.
        run: cd docs && yarn build